---------------------- Correr en session de Playa Cacao---------------------

--Creacion de la tabla de Clientes
CREATE TABLE CLIENTES(
    CEDULA NUMBER CONSTRAINT CEDULA_PK PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    NUMERO_DE_TELEFONO VARCHAR(20)
)

ALTER TABLE CLIENTES MOVE TABLESPACE PLAYA_CACAO_TBS;

--Creacion de la tabla de empleados
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO NUMBER CONSTRAINT ID_EMPLEADO_PK PRIMARY KEY,
    ID_DEPARTAMENTO NUMBER,
    ID_PUESTO NUMBER,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    SALARIO NUMBER,
    CEDULA NUMBER
)

ALTER TABLE EMPLEADOS MOVE TABLESPACE PLAYA_CACAO_TBS;

--Creacion de la tabla correo_clientes
CREATE TABLE CORREO_CLIENTES(
    DIRECCION_DE_CORREO VARCHAR(100) PRIMARY KEY,
    CORREO_DE_RESPALDO VARCHAR(100),
    CEDULA_CLIENTE NUMBER
)

ALTER TABLE CORREO_CLIENTES MOVE TABLESPACE PLAYA_CACAO_TBS;

ALTER TABLE CORREO_CLIENTES
ADD CONSTRAINT CEDULA_CLIENTE_CORREO_FK
    FOREIGN KEY(CEDULA_CLIENTE)
    REFERENCES CLIENTES(CEDULA);

--Creacion de la tabla correo_empleados
CREATE TABLE CORREO_EMPLEADOS(
    DIRECCION_DE_CORREO VARCHAR(100) PRIMARY KEY,
    CORREO_DE_RESPALDO VARCHAR(100),
    ID_EMPLEADO_CORREO NUMBER
)

ALTER TABLE CORREO_EMPLEADOS MOVE TABLESPACE PLAYA_CACAO_TBS;

ALTER TABLE CORREO_EMPLEADOS
ADD CONSTRAINT ID_EMPLEADO_CORREO_FK
    FOREIGN KEY(ID_EMPLEADO_CORREO)
    REFERENCES EMPLEADOS(ID_EMPLEADO);

--Creacion de la tabla Usuarios
CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER CONSTRAINT ID_USUARIO_PK PRIMARY KEY,
    CORREO VARCHAR(100),
    PASSWORD VARCHAR(100),
    ROL_ID NUMBER
)

ALTER TABLE USUARIOS MOVE TABLESPACE PLAYA_CACAO_TBS;

--CREACION DE LA TABLA PUESTOS
CREATE TABLE PUESTOS(
    ID_PUESTO NUMBER CONSTRAINT ID_PUESTO_PK PRIMARY KEY,
    NOMBRE_PUESTO VARCHAR(50),
    SALARIO_BASE NUMBER,
    DESCRIPCION VARCHAR(255)
);

--CREACION DE LA TABLA PUESTOS
CREATE TABLE DEPARTAMENTOS(
    ID_DEPARTAMENTO NUMBER CONSTRAINT ID_DEPARTAMENTO_PK PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(50),
    DESCRIPCION VARCHAR(255)
);


--Creacion de la tabla de Pedidos
CREATE TABLE PEDIDOS(
    ID_PEDIDO NUMBER CONSTRAINT ID_PEDIDO_PK PRIMARY KEY,
    CEDULA_CLIENTE NUMBER,
    ID_PLATILLO NUMBER,
    ID_COMPRA NUMBER,
    TOTAL NUMBER,
    CANTIDAD_PRODUCTOS NUMBER
);

ALTER TABLE PEDIDOS
ADD CONSTRAINT CEDULA_CLIENTE_PEDIDOS_FK
    FOREIGN KEY(CEDULA_CLIENTE)
    REFERENCES CLIENTES(CEDULA);

ALTER TABLE PEDIDOS MOVE TABLESPACE PLAYA_CACAO_TBS;

--DROP TABLE PEDIDOS;

--Creacion de la tabla Compras
CREATE TABLE COMPRAS (
    ID_COMPRA NUMBER CONSTRAINT ID_FACTURA_PK PRIMARY KEY,
    PAGO_TOTAL NUMBER,
    CEDULA_CLIENTE NUMBER
);

ALTER TABLE PEDIDOS MOVE TABLESPACE PLAYA_CACAO_TBS;

ALTER TABLE COMPRAS
ADD CONSTRAINT CEDULA_CLIENTE_COMPRAS_FK
    FOREIGN KEY(CEDULA_CLIENTE)
    REFERENCES CLIENTES(CEDULA)

--Creacion de la tabla de Facturas
CREATE TABLE Facturas (
    ID_FACTURA NUMBER CONSTRAINT ID_FACTURAS_PK PRIMARY KEY,
    ID_COMPRA NUMBER,
    CEDULA_CLIENTE NUMBER,
    METODO_DE_PAGO VARCHAR(250)
);

ALTER TABLE Facturas MOVE TABLESPACE PLAYA_CACAO_TBS;

ALTER TABLE Facturas
ADD CONSTRAINT CEDULA_CLIENTE_Facturas_FK
    FOREIGN KEY(CEDULA_CLIENTE)
    REFERENCES CLIENTES(CEDULA)

ALTER TABLE Facturas
ADD CONSTRAINT ID_COMPRAS_Facturas_FK
    FOREIGN KEY(ID_COMPRA)
    REFERENCES COMPRAS(ID_COMPRA)

--Creacion de la tabla de RESERVAS
CREATE TABLE Reservas (
    ID_RESERVA NUMBER CONSTRAINT ID_MESA_PK PRIMARY KEY,
    DISPONIBILIDAD CHAR(1) DEFAULT 'S', -- Usamos 'S' para disponible y 'N' para no disponible
    ID_CLIENTE NUMBER,
    MESA NUMBER,
    HORA TIMESTAMP
);

ALTER TABLE Reservas MOVE TABLESPACE PLAYA_CACAO_TBS;

ALTER TABLE Reservas
ADD CONSTRAINT CEDULA_CLIENTE_Reservas_FK
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTES(CEDULA)

--Creacion de la tabla de MENU
CREATE TABLE Menu (
    ID_MENU NUMBER CONSTRAINT ID_MENU_PK PRIMARY KEY,
    NOMBRE_MENU VARCHAR2(100),
    DESCRIPCION VARCHAR2(255), 
    DISPONIBLE CHAR(1) DEFAULT 'S' -- Usamos 'S' para disponible y 'N' para no disponible
);

ALTER TABLE PLATILLOS MOVE TABLESPACE PLAYA_CACAO_TBS;

--Creacion de la tabla Platillos
CREATE TABLE PLATILLOS(
    ID_PLATILLO NUMBER CONSTRAINT ID_PLATILLO_PK PRIMARY KEY,
    NOMBRE VARCHAR(250),
    PRECIO_UNITARIO NUMBER,
    CANTIDAD NUMBER,
    ID_MENU NUMBER
);

ALTER TABLE PLATILLOS
ADD CONSTRAINT MENU_ID_PLATILLOS_FK
    FOREIGN KEY(ID_MENU)
    REFERENCES Menu(ID_MENU)

ALTER TABLE PLATILLOS MOVE TABLESPACE PLAYA_CACAO_TBS;



/*ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIO_CLIENTE_CORREO_FK
    FOREIGN KEY(CORREO)
    REFERENCES CORREO_CLIENTES(DIRECCION_DE_CORREO);

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIO_EMPLEADO_CORREO_FK
    FOREIGN KEY(CORREO)
    REFERENCES CORREO_EMPLEADOS(DIRECCION_DE_CORREO);*/