-- Creaci�n de vistas
CREATE OR REPLACE VIEW VISTA_EMPLEADOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS;
 
CREATE OR REPLACE VIEW VISTA_CLIENTES AS
SELECT CEDULA, NOMBRE, APELLIDO, NUMERO_DE_TELEFONO FROM CLIENTES;
 
CREATE OR REPLACE VIEW VISTA_USUARIOS AS
SELECT ID_USUARIO, CORREO, ROL_ID FROM USUARIOS;
 
CREATE OR REPLACE VIEW VISTA_CORREOS_CLIENTES AS
SELECT DIRECCION_DE_CORREO, CEDULA_CLIENTE FROM CORREO_CLIENTES;
 
CREATE OR REPLACE VIEW VISTA_CORREOS_EMPLEADOS AS
SELECT DIRECCION_DE_CORREO, ID_EMPLEADO_CORREO FROM CORREO_EMPLEADOS;
 
CREATE OR REPLACE VIEW VISTA_EMPLEADOS_COMPLETA AS
SELECT E.ID_EMPLEADO, E.NOMBRE, E.APELLIDO, E.SALARIO, C.DIRECCION_DE_CORREO
FROM EMPLEADOS E
LEFT JOIN CORREO_EMPLEADOS C ON E.ID_EMPLEADO = C.ID_EMPLEADO_CORREO;
 
CREATE OR REPLACE VIEW VISTA_CLIENTES_COMPLETA AS
SELECT C.CEDULA, C.NOMBRE, C.APELLIDO, C.NUMERO_DE_TELEFONO, CO.DIRECCION_DE_CORREO
FROM CLIENTES C
LEFT JOIN CORREO_CLIENTES CO ON C.CEDULA = CO.CEDULA_CLIENTE;
 
CREATE OR REPLACE VIEW VISTA_SALARIOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS WHERE SALARIO > 3000;
 
CREATE OR REPLACE VIEW VISTA_ROLES_USUARIOS AS
SELECT U.ID_USUARIO, U.CORREO, U.ROL_ID FROM USUARIOS U WHERE U.ROL_ID IS NOT NULL;
 
CREATE OR REPLACE VIEW VISTA_TELEFONOS_CLIENTES AS
SELECT NOMBRE, APELLIDO, NUMERO_DE_TELEFONO FROM CLIENTES WHERE NUMERO_DE_TELEFONO IS NOT NULL;

------------------------------ VISTA PERSONAS --------------------------------------
CREATE OR REPLACE VIEW VISTA_PERSONAS AS
SELECT 
    CEDULA, 
    NOMBRE, 
    APELLIDO, 
    NUMERO_DE_TELEFONO, 
    ID_ROL_PERSONA, 
    DIRECCION_DE_CORREO, 
    ID_DIRECCION, 
    ID_ESTADO
FROM PERSONAS;
/

------------------------------ VISTA EMPLEADOS COMPLETO ----------------------------
CREATE OR REPLACE VIEW VISTA_EMPLEADOS_COMPLETO AS
SELECT 
    E.ID_EMPLEADO, 
    P.NOMBRE, 
    P.APELLIDO, 
    D.NOMBRE_DEPARTAMENTO, 
    PU.NOMBRE_PUESTO, 
    E.SALARIO
FROM EMPLEADOS E
JOIN PERSONAS P ON E.CEDULA = P.CEDULA
JOIN DEPARTAMENTOS D ON E.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
JOIN PUESTOS PU ON E.ID_PUESTO = PU.ID_PUESTO;
/

------------------------------ VISTA PLATILLOS --------------------------------------
CREATE OR REPLACE VIEW VISTA_PLATILLOS AS
SELECT 
    ID_PLATILLO, 
    NOMBRE_PLATILLO, 
    PRECIO_UNITARIO, 
    CANTIDAD
FROM PLATILLOS
WHERE ID_ESTADO IS NOT NULL;
/

------------------------------ VISTA PEDIDOS CLIENTES -------------------------------
CREATE OR REPLACE VIEW VISTA_PEDIDOS_CLIENTES AS
SELECT 
    P.ID_PEDIDO, 
    PER.NOMBRE || ' ' || PER.APELLIDO AS CLIENTE, 
    P.MONTO_ESTIMADO
FROM PEDIDOS P
JOIN PERSONAS PER ON P.CEDULA_CLIENTE = PER.CEDULA;
/

------------------------------ VISTA FACTURAS ---------------------------------------
CREATE OR REPLACE VIEW VISTA_FACTURAS AS
SELECT 
    F.ID_FACTURA, 
    PER.NOMBRE || ' ' || PER.APELLIDO AS CLIENTE, 
    F.MONTO_TOTAL, 
    F.VUELTO
FROM FACTURAS F
JOIN PERSONAS PER ON F.CEDULA_CLIENTE = PER.CEDULA;
/

------------------------------ VISTA RESERVACIONES ----------------------------------
CREATE OR REPLACE VIEW VISTA_RESERVACIONES AS
SELECT 
    R.ID_RESERVA, 
    P.NOMBRE || ' ' || P.APELLIDO AS CLIENTE, 
    R.MESA, 
    R.ID_HORARIO, 
    R.CONFIRMACION
FROM RESERVACIONES R
JOIN PERSONAS P ON R.CEDULA_CLIENTE = P.CEDULA;
/

------------------------------ VISTA MENU COMPLETO ----------------------------------
CREATE OR REPLACE VIEW VISTA_MENU_COMPLETO AS
SELECT 
    M.ID_MENU, 
    M.NOMBRE_MENU, 
    M.DESCRIPCION, 
    PL.NOMBRE_PLATILLO
FROM MENU M
JOIN PLATILLOS_MENU PM ON M.ID_PLATILLOS_MENU = PM.ID_PLATILLOS_MENU
JOIN PLATILLOS PL ON PM.ID_PLATILLO = PL.ID_PLATILLO;
/
