-- Creaci�n de vistas
CREATE OR REPLACE VIEW VISTA_EMPLEADOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS;
 
CREATE OR REPLACE VIEW VISTA_CLIENTES AS
SELECT CEDULA, NOMBRE, APELLIDO, NUMERO_DE_TELEFONO FROM CLIENTES;
 
CREATE OR REPLACE VIEW VISTA_USUARIOS AS
SELECT ID_USUARIO, CORREO, ROL_ID FROM USUARIOS;
 
CREATE OR REPLACE VIEW VISTA_CORREOS_CLIENTES AS
SELECT DIRECCION_DE_CORREO, CEDULA_CLIENTE FROM CORREO_CLIENTES;
 
CREATE OR REPLACE VIEW VISTA_CORREOS_EMPLEADOS AS
SELECT DIRECCION_DE_CORREO, ID_EMPLEADO_CORREO FROM CORREO_EMPLEADOS;
 
CREATE OR REPLACE VIEW VISTA_EMPLEADOS_COMPLETA AS
SELECT E.ID_EMPLEADO, E.NOMBRE, E.APELLIDO, E.SALARIO, C.DIRECCION_DE_CORREO
FROM EMPLEADOS E
LEFT JOIN CORREO_EMPLEADOS C ON E.ID_EMPLEADO = C.ID_EMPLEADO_CORREO;
 
CREATE OR REPLACE VIEW VISTA_CLIENTES_COMPLETA AS
SELECT C.CEDULA, C.NOMBRE, C.APELLIDO, C.NUMERO_DE_TELEFONO, CO.DIRECCION_DE_CORREO
FROM CLIENTES C
LEFT JOIN CORREO_CLIENTES CO ON C.CEDULA = CO.CEDULA_CLIENTE;
 
CREATE OR REPLACE VIEW VISTA_SALARIOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS WHERE SALARIO > 3000;
 
CREATE OR REPLACE VIEW VISTA_ROLES_USUARIOS AS
SELECT U.ID_USUARIO, U.CORREO, U.ROL_ID FROM USUARIOS U WHERE U.ROL_ID IS NOT NULL;
 
CREATE OR REPLACE VIEW VISTA_TELEFONOS_CLIENTES AS
SELECT NOMBRE, APELLIDO, NUMERO_DE_TELEFONO FROM CLIENTES WHERE NUMERO_DE_TELEFONO IS NOT NULL;
