-------------------------- VISTA PEDIDO PLATILLOS --------------------------------------

CREATE MATERIALIZED VIEW VISTA_PEDIDOS_PLATILLOS
REFRESH COMPLETE ON DEMAND 
AS
    SELECT 
        LP.ID_LISTA_PLATILLOS AS ID_Entrada_lista,
        LP.ID_PEDIDO AS Lista_ID_Pedido,
        LP.ID_PLATILLO AS ID_Platillo,
        LP.ID_ESTADO AS ID_ESTADO,
        PL.NOMBRE_PLATILLO AS Nombre_Platillo,
        PL.PRECIO_UNITARIO AS Precio_del_Platillo,
        P.CEDULA_CLIENTE AS Cedula_Cliente_Pedido,
        C.NOMBRE AS Nombre_Cliente,
        C.APELLIDO AS Apellido_Cliente,
        P.ESTADO_PEDIDO AS Estado_Pedido,
        E.ESTADO AS ESTADO_FILA
    FROM LISTA_PLATILLOS LP
    JOIN PEDIDOS P ON LP.ID_PEDIDO = P.ID_PEDIDO
    JOIN PLATILLOS PL ON LP.ID_PLATILLO = PL.ID_PLATILLO
    JOIN PERSONAS C ON P.CEDULA_CLIENTE = C.CEDULA
    JOIN ESTADOS E ON LP.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';

--SELECT * FROM VISTA_PEDIDOS_PLATILLOS;


--DROP MATERIALIZED VIEW VISTA_PEDIDOS_PLATILLOS;


------------------------------ VISTA PERSONAS --------------------------------------
CREATE OR REPLACE VIEW VISTA_PERSONAS_COMPLETA
AS
    SELECT 
        P.CEDULA AS CEDULA, 
        P.NOMBRE AS NOMBRE, 
        P.APELLIDO AS APELLIDO, 
        P.NUMERO_DE_TELEFONO AS NUMERO_DE_TELEFONO, 
        P.ID_ROL_PERSONA AS ID_ROL,
        ROL.NOMBRE_LARGO_TIPO AS NOMBRE_ROL, 
        P.DIRECCION_DE_CORREO AS DIRECCION_DE_CORREO,
        CR.CORREO_DE_RESPALDO AS CORREO_DE_RESPALDO, 
        P.ID_DIRECCION AS ID_DIRECCION,
        DP.ID_DISTRITO AS ID_DISTRITO,
        DP.ID_CANTON AS ID_CANTON,
        DP.ID_PROVINCIA AS ID_PROVINCIA,
        DIR.NOMBRE_DISTRITO AS DISTRITO,
        CAN.NOMBRE_CANTON AS CANTON,
        PROV.NOMBRE_PROVINCIA AS PROVINCIA,
        P.ID_ESTADO AS ID_ESTADO_FILA,
        E.ESTADO AS ESTADO_FILA
    FROM PERSONAS P
    JOIN ROL_PERSONA ROL ON P.ID_ROL_PERSONA = ROL.ID_ROL_PERSONA
    JOIN CORREOS CR ON P.DIRECCION_DE_CORREO = CR.DIRECCION_DE_CORREO
    JOIN DIRECCIONES_PERSONAS DP ON P.ID_DIRECCION = DP.ID_DIRECCION
    JOIN DISTRITO DIR ON DP.ID_DISTRITO = DIR.ID_DISTRITO
    JOIN CANTON CAN ON DP.ID_CANTON = CAN.ID_CANTON
    JOIN PROVINCIA PROV ON DP.ID_PROVINCIA = PROV.ID_PROVINCIA
    JOIN ESTADOS E ON P.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo' AND CEDULA != 777777;

    SELECT * FROM VISTA_PERSONAS_COMPLETA;

------------------------------ VISTA AUTENTICACION --- ----------------------------

CREATE OR REPLACE VIEW VISTA_AUTENTICACION
AS
    SELECT 
        P.PASSWORD_ID,
        P.NOMBRE AS NOMBRE,
        P.DIRECCION_DE_CORREO AS DIRECCION_DE_CORREO,
        P.ID_ROL_PERSONA AS ROL,
        PE.LLAVE AS LLAVE_PASSWORD,
        PE.PASSWORD_VAL AS PASSWORD_VAL,
        RO.NIVEL_PERMISO AS NIVEL_PERMISO,
        E.ESTADO AS ESTADO_FILA
    FROM PERSONAS P
    JOIN ENCRIPCION_PASSWORDS PE ON P.PASSWORD_ID = PE.PASSWORD_ID
    JOIN ROL_PERSONA RO ON P.ID_ROL_PERSONA = RO.ID_ROL_PERSONA
    JOIN ESTADOS E ON P.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';


------------------------------ VISTA EMPLEADOS COMPLETO ----------------------------
CREATE OR REPLACE VIEW VISTA_EMPLEADOS_COMPLETO AS
SELECT 
    E.ID_EMPLEADO, 
    P.NOMBRE, 
    P.APELLIDO, 
    D.NOMBRE_DEPARTAMENTO, 
    PU.NOMBRE_PUESTO, 
    E.SALARIO
FROM EMPLEADOS E
JOIN PERSONAS P ON E.CEDULA = P.CEDULA
JOIN DEPARTAMENTOS D ON E.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
JOIN PUESTOS PU ON E.ID_PUESTO = PU.ID_PUESTO;

------------------------------ VISTA PLATILLOS --------------------------------------
CREATE OR REPLACE VIEW VISTA_PLATILLOS AS
SELECT 
    P.ID_PLATILLO, 
    P.NOMBRE_PLATILLO, 
    P.PRECIO_UNITARIO, 
    P.CANTIDAD,
    E.ESTADO
FROM PLATILLOS P
JOIN ESTADOS E ON E.ID_ESTADO = P.ID_ESTADO
WHERE E.ESTADO = 'Activo';


SELECT * FROM VISTA_PLATILLOS;
------------------------------ VISTA PEDIDOS CLIENTES -------------------------------
CREATE OR REPLACE VIEW VISTA_PEDIDOS_CLIENTES AS
SELECT 
    P.ID_PEDIDO, 
    PER.NOMBRE || ' ' || PER.APELLIDO AS NOMBRE_COMPLETO_CLIENTE,
    PER.CEDULA,
    P.MONTO_ESTIMADO,
    P.ESTADO_PEDIDO
FROM PEDIDOS P
JOIN PERSONAS PER ON P.CEDULA_CLIENTE = PER.CEDULA;


------------------------------ VISTA FACTURAS ---------------------------------------
CREATE OR REPLACE VIEW VISTA_FACTURAS AS
SELECT 
    F.ID_FACTURA, 
    PER.NOMBRE || ' ' || PER.APELLIDO AS CLIENTE, 
    F.MONTO_TOTAL, 
    F.VUELTO
FROM FACTURAS F
JOIN PERSONAS PER ON F.CEDULA_CLIENTE = PER.CEDULA;

------------------------------ VISTA RESERVACIONES ----------------------------------
CREATE OR REPLACE VIEW VISTA_RESERVACIONES AS
SELECT 
    R.ID_RESERVA, 
    P.NOMBRE || ' ' || P.APELLIDO AS CLIENTE, 
    R.MESA, 
    R.ID_HORARIO, 
    R.CONFIRMACION
FROM RESERVACIONES R
JOIN PERSONAS P ON R.CEDULA_CLIENTE = P.CEDULA;

------------------------------ VISTA MENU COMPLETO ----------------------------------
CREATE OR REPLACE VIEW VISTA_MENU_COMPLETO AS
SELECT 
    M.ID_MENU, 
    M.NOMBRE_MENU, 
    M.DESCRIPCION, 
    PL.ID_PLATILLO,
    PL.NOMBRE_PLATILLO
FROM MENU M
JOIN PLATILLOS_MENU PM ON M.ID_MENU = PM.ID_MENU
JOIN PLATILLOS PL ON PM.ID_PLATILLO = PL.ID_PLATILLO;

------------------------------ VISTA PROVINCIA COMPLETA ----------------------------------

CREATE OR REPLACE VIEW VISTA_PROVINCIAS AS
SELECT
    P.ID_PROVINCIA,
    P.NOMBRE_PROVINCIA,
    P.ID_ESTADO,
    E.ESTADO
    FROM PROVINCIA P
    JOIN ESTADOS E ON P.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';


------------------------------ VISTA CANTONES COMPLETA ----------------------------------

CREATE OR REPLACE VIEW VISTA_CANTONES AS
SELECT
    CA.ID_CANTON,
    CA.NOMBRE_CANTON,
    CA.ID_ESTADO,
    E.ESTADO
    FROM CANTON CA
    JOIN ESTADOS E ON CA.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';


------------------------------ VISTA DISTRITOS COMPLETA ----------------------------------

CREATE OR REPLACE VIEW VISTA_DISTRITOS AS
SELECT
    D.ID_DISTRITO,
    D.NOMBRE_DISTRITO,
    D.ID_ESTADO,
    E.ESTADO
    FROM DISTRITO D
    JOIN ESTADOS E ON D.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';

    ------------------------------ VISTA ROLES COMPLETA -------------------------------------

CREATE OR REPLACE VIEW VISTA_ROL_PERSONA AS
SELECT
    RO.ID_ROL_PERSONA,
    RO.NOMBRE_LARGO_TIPO,
    RO.DESCRIPCION DESCRIPCION,
    RO.NIVEL_PERMISO,
    RO.ID_ESTADO,
    E.ESTADO
    FROM ROL_PERSONA RO
    JOIN ESTADOS E ON RO.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';

  ------------------------------ VISTA ROLES COMPLETA -------------------------------------

SELECT * FROM VISTA_PUESTOS;

  CREATE OR REPLACE VIEW VISTA_PUESTOS AS
  SELECT
    P.ID_PUESTO AS ID_PUESTO,
    P.NOMBRE_PUESTO AS NOMBRE_PUESTO,
    P.DESCRIPCION AS DESCRIPCION,
    E.ESTADO AS ESTADO
    FROM PUESTOS P
    JOIN ESTADOS E ON P.ID_ESTADO = E.ID_ESTADO
    WHERE E.ESTADO = 'Activo';

------------------------------ Vista Horarios -------------------------------------

CREATE OR REPLACE VIEW VISTA_HORARIOS AS
SELECT 
    H.ID_HORARIO, 
    H.DISPONIBILIDAD, 
    H.HORA_EXACTA, 
    E.ESTADO
FROM HORARIOS_MESA H
JOIN ESTADOS E ON E.ID_ESTADO = H.ID_ESTADO
WHERE E.ESTADO = 'Activo';


---------------- Vista para obtener cédula a partir del correo ------------------

CREATE OR REPLACE VIEW VISTA_CLIENTES_CEDULA_CORREO AS
SELECT 
    CEDULA,
    DIRECCION_DE_CORREO
FROM PERSONAS
WHERE ID_ESTADO IN (
    SELECT ID_ESTADO
    FROM ESTADOS
    WHERE ESTADO = 'Activo'
);

---- Vista para obtener pedidos por cédula de cliente ------------------

CREATE OR REPLACE VIEW VISTA_PEDIDOS_CLIENTE AS
SELECT 
    P.ID_PEDIDO, 
    P.CEDULA_CLIENTE,
    PER.NOMBRE || ' ' || PER.APELLIDO AS NOMBRE_CLIENTE,
    P.MONTO_ESTIMADO,
    P.ESTADO_PEDIDO
FROM PEDIDOS P
JOIN PERSONAS PER ON PER.CEDULA = P.CEDULA_CLIENTE;

------------------------ Vista Mesas -------------------------------------

CREATE OR REPLACE VIEW VISTA_MESAS AS
SELECT
    M.ID_MESA,
    M.NOMBRE_MESA,
    M.ID_HORARIO,
    M.ID_ESTADO
FROM
    MESAS M
JOIN
    ESTADOS E ON M.ID_ESTADO = E.ID_ESTADO
WHERE
    E.ESTADO = 'Activo';

---------------------- Vista de Mesas Disponibles -------------------------------

CREATE OR REPLACE VIEW VISTA_MESAS_DISPONIBLES AS
SELECT
    M.ID_MESA,
    M.NOMBRE_MESA,
    M.ID_HORARIO,
    H.HORA_EXACTA
FROM
    MESAS M
JOIN ESTADOS E ON M.ID_ESTADO = E.ID_ESTADO
JOIN HORARIOS_MESA H ON M.ID_HORARIO = H.ID_HORARIO
WHERE
    E.ESTADO = 'Activo' AND H.DISPONIBILIDAD = 'Disponible';
