----- Eliminar Platillo -----

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_PLATILLO (
    P_ID_PLATILLO IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('PLATILLOS', P_ID_PLATILLO, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_PLATILLO(P_ID_PLATILLO);
        RETURN 'BORRADO_FISICO';
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

------------ ---------------------- ELIMINAR MENU ------------------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_MENU (
    P_ID_MENU IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('MENU', P_ID_MENU, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_MENU(P_ID_MENU);
        RETURN 'BORRADO_FISICO';
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/