----- Eliminar Platillo -----

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_PLATILLO (
    P_ID_PLATILLO IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('PLATILLOS', P_ID_PLATILLO, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_PLATILLO(P_ID_PLATILLO);
        RETURN 'BORRADO_FISICO';
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

------------ ---------------------- ELIMINAR MENU ------------------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_MENU (
    P_ID_MENU IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('MENU', P_ID_MENU, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_MENU(P_ID_MENU);
        RETURN 'BORRADO_FISICO';
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/


------------ ---------------------- ELIMINAR HORARIO ------------------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_HORARIO (
    P_ID_HORARIO IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('HORARIOS_MESA', P_ID_HORARIO, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_HORARIO(P_ID_HORARIO, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/


---------------- ELIMINAR MESA ------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_MESA (
    P_ID_MESA IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('MESAS', P_ID_MESA, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_MESA(P_ID_MESA, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

---------------- ELIMINAR PEDIDO ------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_PEDIDO (
    P_ID_PEDIDO IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('PEDIDOS', P_ID_PEDIDO, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_PEDIDO(P_ID_PEDIDO, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

---------------- ELIMINAR METODO DE PAGO ------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_METODO_PAGO (
    P_ID_METODO IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('METODO_PAGO', P_ID_METODO, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_METODO_PAGO(P_ID_METODO, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

---------------- ELIMINAR FACTURA ------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_FACTURA (
    P_ID_FACTURA IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('FACTURAS', P_ID_FACTURA, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_FACTURA(P_ID_FACTURA, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

---------------- ELIMINAR RESERVACION ------------------

CREATE OR REPLACE FUNCTION EJECUTAR_BORRADO_RESERVACION (
    P_ID_RESERVA IN NUMBER,
    P_TIPO IN VARCHAR,
    P_COMENTARIO IN VARCHAR
) RETURN VARCHAR
AS
    V_RESULTADO VARCHAR(50);
BEGIN
    IF LOWER(P_TIPO) = 'logico' THEN
        BORRADO_LOGICO('RESERVACIONES', P_ID_RESERVA, P_COMENTARIO);
        RETURN 'BORRADO_LOGICO';
    ELSIF LOWER(P_TIPO) = 'fisico' THEN
        ELIMINAR_RESERVACION(P_ID_RESERVA, V_RESULTADO);
        RETURN V_RESULTADO;
    ELSE
        RETURN 'TIPO_INVALIDO';
    END IF;
END;
/

