------------------- Funcion para calcular el monto total de un pedido --------------------------

/*
CREATE OR REPLACE FUNCTION CALCULAR_TOTAL_PEDIDO(
    P_ID_PEDIDO NUMBER
) 
RETURN NUMBER
AS
    V_TOTAL NUMBER;
BEGIN

    SELECT SUM(Precio_del_Platillo) 
    INTO V_TOTAL
    FROM VISTA_PEDIDOS_PLATILLOS
    WHERE Lista_ID_Pedido = P_ID_PEDIDO;

    RETURN V_TOTAL;

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        V_TOTAL := 0;
        RETURN V_TOTAL;

END;

------------------------------ CREAR PEDIDO --------------------------------------
CREATE OR REPLACE PROCEDURE CREAR_PEDIDO(
    P_CEDULA_CLIENTE NUMBER,
    P_MONTO_ESTIMADO NUMBER,
    P_ESTADO_PEDIDO VARCHAR,
    P_COMENTARIO VARCHAR
)
AS
    V_ID_PEDIDO NUMBER;
    V_ESTADO_ID VARCHAR(250);
BEGIN
    INSERT INTO PEDIDOS(CEDULA_CLIENTE, MONTO_ESTIMADO, ESTADO_PEDIDO)
    VALUES (P_CEDULA_CLIENTE, P_MONTO_ESTIMADO,P_ESTADO_PEDIDO);

    SELECT ID_PEDIDO INTO V_ID_PEDIDO
    FROM PEDIDOS
    WHERE CEDULA_CLIENTE = P_CEDULA_CLIENTE
    ORDER BY ID_PEDIDO DESC FETCH FIRST 1 ROW ONLY;

    V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_PEDIDO), 'PEDIDOS', P_COMENTARIO);

    UPDATE PEDIDOS
    SET ID_ESTADO = V_ESTADO_ID
    WHERE ID_PEDIDO = V_ID_PEDIDO;

    COMMIT;
END;
/

------------------------------CREAR METODO DE PAGO ------------------------------

CREATE OR REPLACE PROCEDURE CREAR_METODO_DE_PAGO(
    P_NOMBRE_METODO VARCHAR,
    P_DESCRIPCION VARCHAR,
    P_COMENTARIO VARCHAR
)
AS
    V_ESTADO_ID VARCHAR(250);
    V_ID_METODO NUMBER;

BEGIN
    --Insercion del distrito
    INSERT INTO METODO_PAGO(NOMBRE_METODO, DESCRIPCION)
     VALUES (P_NOMBRE_METODO, P_DESCRIPCION);
    
    SELECT ID_METODO
        INTO V_ID_METODO
        FROM METODO_PAGO
        WHERE NOMBRE_METODO = P_NOMBRE_METODO;
    
    --Creamos el estado llamando a la funcion delegada
    V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_METODO),'METODO_PAGO', P_COMENTARIO);
    
    --Actualizamos el id del estado
    UPDATE METODO_PAGO
    SET ID_ESTADO = V_ESTADO_ID
    WHERE ID_METODO = V_ID_METODO;
    
    COMMIT;

END;
/


------------------------------CREAR LISTA DE PLATILLOS --------------------------

CREATE OR REPLACE PROCEDURE CREAR_ENTRADA_LISTA_PLATILLOS(
    P_ID_PLATILLO NUMBER,
    P_ID_PEDIDO NUMBER,
    P_COMENTARIO VARCHAR
)
AS
    V_ID_ENTRADA NUMBER;
    V_ID_ESTADO VARCHAR(250);

BEGIN

    INSERT INTO LISTA_PLATILLOS(ID_PLATILLO, ID_PEDIDO)
    VALUES (P_ID_PLATILLO, P_ID_PEDIDO) 
    RETURNING ID_LISTA_PLATILLOS INTO V_ID_ENTRADA;

    V_ID_ESTADO := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_ENTRADA), 'LISTA_PLATILLOS', P_COMENTARIO);

    UPDATE LISTA_PLATILLOS
    SET ID_ESTADO = V_ID_ESTADO
    WHERE ID_LISTA_PLATILLOS = V_ID_ENTRADA;

    COMMIT;
END;
/
----------------------------Actualizar el monto total de un pedido----------------

CREATE OR REPLACE PROCEDURE ACTUALIZAR_TOTAL_PEDIDO(
    P_ID_PEDIDO NUMBER
)
AS 
    V_TOTAL_ESTIMADO NUMBER;
BEGIN
    V_TOTAL_ESTIMADO := CALCULAR_TOTAL_PEDIDO(P_ID_PEDIDO);

    UPDATE PEDIDOS
    SET MONTO_ESTIMADO = V_TOTAL_ESTIMADO
    WHERE ID_PEDIDO = P_ID_PEDIDO;

    COMMIT;
END;
------------------------------ CREAR FACTURA -------------------------------------

CREATE OR REPLACE PROCEDURE CREAR_FACTURA(

    P_ID_PEDIDO NUMBER,
    P_ID_METODO NUMBER,
    P_VUELTO NUMBER,
    P_COMENTARIO VARCHAR
)

AS
    V_ID_FACTURA NUMBER;

    V_ESTADO_ID VARCHAR(250);
    V_MONTO NUMBER;
    V_CEDULA_CLIENTE NUMBER;
    V_NOMBRE_CLIENTE VARCHAR(100);

BEGIN
    ACTUALIZAR_TOTAL_PEDIDO(P_ID_PEDIDO);

    SELECT Nombre_Completo_cliente, MONTO_ESTIMADO, CEDULA
    INTO V_NOMBRE_CLIENTE, V_MONTO, V_CEDULA_CLIENTE
    FROM VISTA_PEDIDOS_CLIENTES;

    INSERT INTO FACTURAS(CEDULA_CLIENTE, ID_PEDIDO, ID_METODO, MONTO_TOTAL, NOMBRE_CLIENTE, VUELTO)
    VALUES (V_CEDULA_CLIENTE, P_ID_PEDIDO, P_ID_METODO, V_MONTO, V_NOMBRE_CLIENTE, P_VUELTO)
    RETURNING ID_FACTURA INTO V_ID_FACTURA;

    V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_FACTURA), 'FACTURAS', P_COMENTARIO);

    UPDATE FACTURAS
    SET ID_ESTADO = V_ESTADO_ID
    WHERE ID_FACTURA = V_ID_FACTURA;

    UPDATE LISTA_PLATILLOS
    SET ID_FACTURA = V_ID_FACTURA
    WHERE P_ID_PEDIDO = P_ID_PEDIDO;

    UPDATE PEDIDOS
    SET ESTADO_PEDIDO = 'Completo'
    WHERE P_ID_PEDIDO = P_ID_PEDIDO;

    COMMIT;
END;
/

------------------------------ ACTUALIZAR PEDIDO ---------------------------------------
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PEDIDO(
    P_ID_PEDIDO NUMBER,
    P_NUEVO_MONTO_ESTIMADO NUMBER
)
AS
BEGIN
    UPDATE PEDIDOS
    SET MONTO_ESTIMADO = P_NUEVO_MONTO_ESTIMADO
    WHERE ID_PEDIDO = P_ID_PEDIDO;
    COMMIT;
END;
/

------------------------------ ACTUALIZAR FACTURA --------------------------------------
CREATE OR REPLACE PROCEDURE ACTUALIZAR_FACTURA(
    P_ID_FACTURA NUMBER,
    P_NUEVO_MONTO_TOTAL NUMBER,
    P_NUEVO_VUELTO NUMBER
)
AS
BEGIN
    UPDATE FACTURAS
    SET MONTO_TOTAL = P_NUEVO_MONTO_TOTAL,
        VUELTO = P_NUEVO_VUELTO
    WHERE ID_FACTURA = P_ID_FACTURA;
    COMMIT;
END;
/
*/