CREATE OR REPLACE PROCEDURE ELIMINAR_PEDIDO (
    P_ID_PEDIDO IN NUMBER,
    P_RESULTADO OUT VARCHAR
)
AS
    V_ID_ESTADO VARCHAR(250);
    V_EXISTE_FACTURA NUMBER := 0;
BEGIN
    -- Verificar si existe alguna factura asociada al pedido
    SELECT COUNT(*) INTO V_EXISTE_FACTURA
    FROM FACTURAS
    WHERE ID_PEDIDO = P_ID_PEDIDO;

    IF V_EXISTE_FACTURA > 0 THEN
        P_RESULTADO := 'REFERENCIAS_ACTIVAS';
        RETURN;
    END IF;

    -- Obtener ID_ESTADO del pedido
    SELECT ID_ESTADO INTO V_ID_ESTADO
    FROM PEDIDOS
    WHERE ID_PEDIDO = P_ID_PEDIDO;

    -- Eliminar lista de platillos del pedido
    DELETE FROM LISTA_PLATILLOS WHERE ID_PEDIDO = P_ID_PEDIDO;

    -- Eliminar el pedido
    DELETE FROM PEDIDOS WHERE ID_PEDIDO = P_ID_PEDIDO;

    -- Eliminar el estado asociado
    DELETE FROM ESTADOS WHERE ID_ESTADO = V_ID_ESTADO;

    COMMIT;

    P_RESULTADO := 'BORRADO_FISICO';
END;
/
