CREATE OR REPLACE PACKAGE PKG_FACTURAS AS
    PROCEDURE CREAR_FACTURA(
        P_CEDULA_CLIENTE NUMBER,
        P_ID_PEDIDO NUMBER,
        P_ID_METODO NUMBER,
        P_MONTO_TOTAL NUMBER,
        P_NOMBRE_CLIENTE VARCHAR,
        P_VUELTO NUMBER,
        P_DESCUENTO NUMBER,
        P_IVA NUMBER,
        P_COMENTARIO VARCHAR
    );

    PROCEDURE MODIFICAR_FACTURA(
        P_ID_FACTURA NUMBER,
        P_ID_METODO NUMBER,
        P_VUELTO NUMBER,
        P_DESCUENTO NUMBER,
        P_IVA NUMBER
    );

    PROCEDURE ELIMINAR_FACTURA(
        P_ID_FACTURA NUMBER,
        P_COMENTARIO VARCHAR
    );

    PROCEDURE ENVIO_FACTURAS_ADMIN(P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE ENVIO_FACTURAS_CLIENTE(P_CEDULA NUMBER, P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE ENVIO_FACTURA_INDIVIDUAL(P_ID_FACTURA NUMBER, P_CURSOR OUT SYS_REFCURSOR);
END PKG_FACTURAS;
/


CREATE OR REPLACE PACKAGE BODY PKG_FACTURAS AS

    PROCEDURE CREAR_FACTURA(
        P_CEDULA_CLIENTE NUMBER,
        P_ID_PEDIDO NUMBER,
        P_ID_METODO NUMBER,
        P_MONTO_TOTAL NUMBER,
        P_NOMBRE_CLIENTE VARCHAR,
        P_VUELTO NUMBER,
        P_DESCUENTO NUMBER,
        P_IVA NUMBER,
        P_COMENTARIO VARCHAR
    ) AS
        V_ID_FACTURA NUMBER;
        V_ESTADO_ID VARCHAR(250);
    BEGIN
        INSERT INTO FACTURAS (
            CEDULA_CLIENTE, ID_PEDIDO, ID_METODO,
            MONTO_TOTAL, NOMBRE_CLIENTE,
            VUELTO, DESCUENTO, IVA
        )
        VALUES (
            P_CEDULA_CLIENTE, P_ID_PEDIDO, P_ID_METODO,
            P_MONTO_TOTAL, P_NOMBRE_CLIENTE,
            P_VUELTO, P_DESCUENTO, P_IVA
        )
        RETURNING ID_FACTURA INTO V_ID_FACTURA;

        V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_FACTURA), 'FACTURAS', P_COMENTARIO);

        UPDATE FACTURAS
        SET ID_ESTADO = V_ESTADO_ID
        WHERE ID_FACTURA = V_ID_FACTURA;

        COMMIT;
    END;

    PROCEDURE MODIFICAR_FACTURA(
        P_ID_FACTURA NUMBER,
        P_ID_METODO NUMBER,
        P_VUELTO NUMBER,
        P_DESCUENTO NUMBER,
        P_IVA NUMBER
    ) AS
    BEGIN
        UPDATE FACTURAS
        SET ID_METODO = P_ID_METODO,
            VUELTO = P_VUELTO,
            DESCUENTO = P_DESCUENTO,
            IVA = P_IVA
        WHERE ID_FACTURA = P_ID_FACTURA;

        COMMIT;
    END;

    PROCEDURE ELIMINAR_FACTURA(
        P_ID_FACTURA NUMBER,
        P_COMENTARIO VARCHAR
    ) AS
        V_ESTADO_ID VARCHAR(250);
    BEGIN
        V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(P_ID_FACTURA), 'FACTURAS', P_COMENTARIO);

        UPDATE FACTURAS
        SET ID_ESTADO = V_ESTADO_ID
        WHERE ID_FACTURA = P_ID_FACTURA;

        COMMIT;
    END;

    PROCEDURE ENVIO_FACTURAS_ADMIN(P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM VISTA_FACTURAS;
    END;

    PROCEDURE ENVIO_FACTURAS_CLIENTE(P_CEDULA NUMBER, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM VISTA_FACTURAS WHERE CEDULA_CLIENTE = P_CEDULA;
    END;

    PROCEDURE ENVIO_FACTURA_INDIVIDUAL(P_ID_FACTURA NUMBER, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM VISTA_FACTURAS WHERE ID_FACTURA = P_ID_FACTURA;
    END;

END PKG_FACTURAS;
/
