create or replace PACKAGE PKG_PUESTOS AS
    PROCEDURE AGREGAR_PUESTO(
        P_NOMBRE_PUESTO VARCHAR,
        P_SALARIO_BASE NUMBER,
        P_DESCRIPCION VARCHAR
    );

    PROCEDURE MODIFICAR_PUESTO(
        P_ID_PUESTO NUMBER,
        P_NOMBRE_PUESTO VARCHAR,
        P_SALARIO_BASE NUMBER,
        P_DESCRIPCION VARCHAR
    );

    PROCEDURE ELIMINAR_PUESTO(P_ID_PUESTO NUMBER);

    PROCEDURE ENVIO_TOTAL_PUESTOS(P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE ENVIO_PUESTO_INDIVIDUAL(P_ID_PUESTO NUMBER, P_CURSOR OUT SYS_REFCURSOR);
END PKG_PUESTOS;


create or replace PACKAGE BODY PKG_PUESTOS AS

    PROCEDURE AGREGAR_PUESTO(
        P_NOMBRE_PUESTO VARCHAR,
        P_SALARIO_BASE NUMBER,
        P_DESCRIPCION VARCHAR
    ) AS
        V_ID_PUESTO NUMBER;
        V_ESTADO_ID VARCHAR(250);
    BEGIN
        INSERT INTO PUESTOS(NOMBRE_PUESTO, SALARIO_BASE, DESCRIPCION)
        VALUES (P_NOMBRE_PUESTO, P_SALARIO_BASE, P_DESCRIPCION)
        RETURNING ID_PUESTO INTO V_ID_PUESTO;

        V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(V_ID_PUESTO), 'PUESTOS', 'Creación de puesto');

        UPDATE PUESTOS SET ID_ESTADO = V_ESTADO_ID WHERE ID_PUESTO = V_ID_PUESTO;

        COMMIT;
    END;

    PROCEDURE MODIFICAR_PUESTO(
        P_ID_PUESTO NUMBER,
        P_NOMBRE_PUESTO VARCHAR,
        P_SALARIO_BASE NUMBER,
        P_DESCRIPCION VARCHAR
    ) AS
    BEGIN
        UPDATE PUESTOS
        SET NOMBRE_PUESTO = P_NOMBRE_PUESTO,
            SALARIO_BASE = P_SALARIO_BASE,
            DESCRIPCION = P_DESCRIPCION
        WHERE ID_PUESTO = P_ID_PUESTO;

        COMMIT;
    END;

    PROCEDURE ELIMINAR_PUESTO(P_ID_PUESTO NUMBER) AS
        V_ESTADO_ID VARCHAR(250);
    BEGIN
        V_ESTADO_ID := CREAR_ENTRADA_ESTADO(TO_CHAR(P_ID_PUESTO), 'PUESTOS', 'Eliminación de puesto');

        UPDATE PUESTOS
        SET ID_ESTADO = V_ESTADO_ID
        WHERE ID_PUESTO = P_ID_PUESTO;

        COMMIT;
    END;

    PROCEDURE ENVIO_TOTAL_PUESTOS(P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM VISTA_PUESTOS;
    END;

    PROCEDURE ENVIO_PUESTO_INDIVIDUAL(P_ID_PUESTO NUMBER, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
        SELECT * FROM VISTA_PUESTOS WHERE ID_PUESTO = P_ID_PUESTO;
    END;

END PKG_PUESTOS;
