-- Inserciones realistas para la tabla PLATILLOS
EXEC CREAR_PLATILLO('Arroz con Pollo', 3500, 120, 'Platillo típico costarricense');
EXEC CREAR_PLATILLO('Casado con Carne', 4000, 110, 'Incluye arroz, frijoles, carne de res');
EXEC CREAR_PLATILLO('Ensalada César con Pollo', 3200, 90, 'Fresca y ligera');
EXEC CREAR_PLATILLO('Pizza Margarita', 4500, 80, 'Base de tomate, albahaca y mozzarella');
EXEC CREAR_PLATILLO('Pasta Alfredo', 4700, 75, 'Salsa cremosa con champiñones');
EXEC CREAR_PLATILLO('Ceviche Mixto', 5000, 65, 'Con camarón y pescado blanco');
EXEC CREAR_PLATILLO('Hamburguesa Clásica', 3800, 100, 'Pan artesanal con carne de res');
EXEC CREAR_PLATILLO('Chifrijo', 4200, 95, 'Frijoles, chicharrón y pico de gallo');
EXEC CREAR_PLATILLO('Tacos al Pastor', 4300, 70, 'Con piña, cebolla y cilantro');
EXEC CREAR_PLATILLO('Sopa Negra', 3000, 85, 'Frijoles negros con huevo duro');
EXEC CREAR_PLATILLO('Quesadillas de Pollo', 3900, 95, 'Tortilla rellena de queso y pollo');
EXEC CREAR_PLATILLO('Arroz Chaufa', 4600, 80, 'Fusión peruana-china con vegetales');
EXEC CREAR_PLATILLO('Filete de Pescado', 5200, 60, 'A la plancha con vegetales');
EXEC CREAR_PLATILLO('Gallo Pinto', 2800, 120, 'Tradicional desayuno tico');
EXEC CREAR_PLATILLO('Panqueques con Miel', 3100, 100, 'Desayuno dulce');
EXEC CREAR_PLATILLO('Burrito de Res', 4100, 90, 'Con frijoles y guacamole');
EXEC CREAR_PLATILLO('Arepas Rellenas', 3500, 85, 'Con carne mechada');
EXEC CREAR_PLATILLO('Pollo Empanizado', 3900, 95, 'Con papas fritas');
EXEC CREAR_PLATILLO('Chow Mein', 4500, 70, 'Fideos salteados estilo chino');
EXEC CREAR_PLATILLO('Crema de Ayote', 3100, 100, 'Sopa cremosa de ayote');
EXEC CREAR_PLATILLO('Tamal Asado', 3200, 75, 'Hecho con masa de maíz y relleno');
EXEC CREAR_PLATILLO('Tortilla Española', 3600, 80, 'Con papa y huevo');
EXEC CREAR_PLATILLO('Empanadas de Frijol', 2900, 95, 'Masa frita con relleno salado');
EXEC CREAR_PLATILLO('Croquetas de Pollo', 3500, 90, 'Crujientes por fuera, suaves por dentro');
EXEC CREAR_PLATILLO('Hamburguesa Vegana', 4000, 70, 'Con torta de garbanzo');
EXEC CREAR_PLATILLO('Pasta al Pesto', 4700, 85, 'Salsa de albahaca y ajo');
EXEC CREAR_PLATILLO('Crepes Dulces', 3100, 80, 'Con nutella y fruta');
EXEC CREAR_PLATILLO('Lasaña de Carne', 4900, 70, 'Capas de pasta, carne y queso');
EXEC CREAR_PLATILLO('Tarta de Queso', 3500, 100, 'Postre frío');
EXEC CREAR_PLATILLO('Canelones de Espinaca', 3700, 75, 'Rellenos vegetarianos');
EXEC CREAR_PLATILLO('Rollos Primavera', 3300, 90, 'Con salsa agridulce');
EXEC CREAR_PLATILLO('Pollo Teriyaki', 4800, 65, 'Estilo japonés');
EXEC CREAR_PLATILLO('Alitas BBQ', 4200, 95, 'Picantes o dulces');
EXEC CREAR_PLATILLO('Cazuela de Mariscos', 5500, 60, 'Con crema y vino blanco');
EXEC CREAR_PLATILLO('Pupusas Revueltas', 3600, 90, 'Queso, frijol y chicharrón');
EXEC CREAR_PLATILLO('Sushi Roll California', 5000, 70, 'Aguacate y surimi');
EXEC CREAR_PLATILLO('Fajitas Mixtas', 4600, 85, 'Res y pollo con vegetales');
EXEC CREAR_PLATILLO('Bistec Encebollado', 4400, 80, 'Clásico costarricense');
EXEC CREAR_PLATILLO('Sándwich Cubano', 4000, 100, 'Con jamón y pepinillo');
EXEC CREAR_PLATILLO('Pizza Hawaiana', 4700, 85, 'Con piña y jamón');
EXEC CREAR_PLATILLO('Cremas Heladas', 3000, 90, 'Diferentes sabores');
EXEC CREAR_PLATILLO('Costillas BBQ', 5600, 70, 'Jugosas y bien cocidas');
EXEC CREAR_PLATILLO('Ensalada de Atún', 3400, 100, 'Fresca con vinagreta');
EXEC CREAR_PLATILLO('Galletas con Helado', 3200, 95, 'Postre muy solicitado');
EXEC CREAR_PLATILLO('Milkshake de Chocolate', 3300, 90, 'Refrescante y dulce');
EXEC CREAR_PLATILLO('Panini de Pollo', 3900, 80, 'Tostado con queso');
EXEC CREAR_PLATILLO('Torta Chilena', 3700, 85, 'Postre tradicional');
EXEC CREAR_PLATILLO('Café Cappuccino', 2800, 120, 'Perfecto para la tarde');
EXEC CREAR_PLATILLO('Brownie con Helado', 3600, 90, 'Combinación perfecta');
