---------------------- Correr en session de Playa Cacao---------------------
/*
Setup inicial de la base de datos, crea el usuario de administrador de la pagina web asi como una cantidad de entradas para empezar a trabajar con la pagina web
*/

EXEC CREAR_DISTRITO('San Antonio', 'Agregando distritos');
EXEC CREAR_DISTRITO('Zapoote', 'Agregando distritos');
EXEC CREAR_DISTRITO('Desamparados', 'Agregando distritos');
EXEC CREAR_DISTRITO('Merced', 'Agregando distritos');
EXEC CREAR_DISTRITO('Hospital', 'Agregando distritos');
EXEC CREAR_DISTRITO('Catedral', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Francisco', 'Agregando distritos');
EXEC CREAR_DISTRITO('Carrizal', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Isidro', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Sebastián', 'Agregando distritos');
EXEC CREAR_DISTRITO('Hatillo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Gravilias', 'Agregando distritos');
EXEC CREAR_DISTRITO('Pavas', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Uruca', 'Agregando distritos');
EXEC CREAR_DISTRITO('Mata Redonda', 'Agregando distritos');
EXEC CREAR_DISTRITO('Zapote', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Juan de Dios', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael Abajo', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael Arriba', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Miguel', 'Agregando distritos');
EXEC CREAR_DISTRITO('Los Guido', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Pedro', 'Agregando distritos');
EXEC CREAR_DISTRITO('Sabanilla', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Vicente', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guadalupe', 'Agregando distritos');
EXEC CREAR_DISTRITO('Ipís', 'Agregando distritos');
EXEC CREAR_DISTRITO('Rancho Redondo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Calle Blancos', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Juan', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Diego', 'Agregando distritos');
EXEC CREAR_DISTRITO('Tres Ríos', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Pablo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santa Rosa', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santiago', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santa Cruz', 'Agregando distritos');
EXEC CREAR_DISTRITO('Paraíso', 'Agregando distritos');
EXEC CREAR_DISTRITO('Orosi', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cachí', 'Agregando distritos');
EXEC CREAR_DISTRITO('Birrisito', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Carlos', 'Agregando distritos');
EXEC CREAR_DISTRITO('Florencia', 'Agregando distritos');
EXEC CREAR_DISTRITO('Quesada', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cutris', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Fortuna', 'Agregando distritos');
EXEC CREAR_DISTRITO('Venado', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Tigra', 'Agregando distritos');
EXEC CREAR_DISTRITO('Monterrey', 'Agregando distritos');
EXEC CREAR_DISTRITO('Pital', 'Agregando distritos');
EXEC CREAR_DISTRITO('Aguas Zarcas', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Isidro de Peñas Blancas', 'Agregando distritos');
EXEC CREAR_DISTRITO('Limón', 'Agregando distritos');
EXEC CREAR_DISTRITO('Valle La Estrella', 'Agregando distritos');
EXEC CREAR_DISTRITO('Matama', 'Agregando distritos');
EXEC CREAR_DISTRITO('Roxana', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cariari', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guápiles', 'Agregando distritos');
EXEC CREAR_DISTRITO('Jiménez', 'Agregando distritos');
EXEC CREAR_DISTRITO('Reventazón', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guácimo', 'Agregando distritos');

-- Creacion de Cantones
EXEC CREAR_Canton('Pérez Zeledón', 'Agregando Cantones');
EXEC CREAR_Canton('Escazú', 'Agregando Cantones');
EXEC CREAR_Canton('Moravia', 'Agregando Cantones');
EXEC CREAR_Canton('Alajuela', 'Agregando Cantones');
EXEC CREAR_Canton('San Ramón', 'Agregando Cantones');
EXEC CREAR_Canton('Grecia', 'Agregando Cantones');
EXEC CREAR_Canton('Atenas', 'Agregando Cantones');
EXEC CREAR_Canton('San Mateo', 'Agregando Cantones');
EXEC CREAR_Canton('Palmares', 'Agregando Cantones');
EXEC CREAR_Canton('Poás', 'Agregando Cantones');
EXEC CREAR_Canton('Orotina', 'Agregando Cantones');
EXEC CREAR_Canton('Desamparados', 'Agregando Cantones');
EXEC CREAR_Canton('Acosta', 'Agregando Cantones');
EXEC CREAR_Canton('Aserrí', 'Agregando Cantones');
EXEC CREAR_Canton('Curridabat', 'Agregando Cantones');
EXEC CREAR_Canton('Goicoechea', 'Agregando Cantones');
EXEC CREAR_Canton('Montes de Oca', 'Agregando Cantones');
EXEC CREAR_Canton('Tibás', 'Agregando Cantones');
EXEC CREAR_Canton('Santa Ana', 'Agregando Cantones');
EXEC CREAR_Canton('Alajuelita', 'Agregando Cantones');
EXEC CREAR_Canton('Vásquez de Coronado', 'Agregando Cantones');
EXEC CREAR_Canton('Puriscal', 'Agregando Cantones');
EXEC CREAR_Canton('Turrubares', 'Agregando Cantones');
EXEC CREAR_Canton('Dota', 'Agregando Cantones');
EXEC CREAR_Canton('Tarrazú', 'Agregando Cantones');
EXEC CREAR_Canton('León Cortés', 'Agregando Cantones');
EXEC CREAR_Canton('Cartago', 'Agregando Cantones');
EXEC CREAR_Canton('Paraíso', 'Agregando Cantones');
EXEC CREAR_Canton('La Unión', 'Agregando Cantones');
EXEC CREAR_Canton('Jiménez', 'Agregando Cantones');
EXEC CREAR_Canton('Turrialba', 'Agregando Cantones');
EXEC CREAR_Canton('Alvarado', 'Agregando Cantones');
EXEC CREAR_Canton('Oreamuno', 'Agregando Cantones');
EXEC CREAR_Canton('El Guarco', 'Agregando Cantones');
EXEC CREAR_Canton('San Carlos', 'Agregando Cantones');
EXEC CREAR_Canton('Zarcero', 'Agregando Cantones');
EXEC CREAR_Canton('Sarchí', 'Agregando Cantones');
EXEC CREAR_Canton('Upala', 'Agregando Cantones');
EXEC CREAR_Canton('Los Chiles', 'Agregando Cantones');
EXEC CREAR_Canton('Guatuso', 'Agregando Cantones');
EXEC CREAR_Canton('Puntarenas', 'Agregando Cantones');
EXEC CREAR_Canton('Esparza', 'Agregando Cantones');
EXEC CREAR_Canton('Buenos Aires', 'Agregando Cantones');
EXEC CREAR_Canton('Montes de Oro', 'Agregando Cantones');
EXEC CREAR_Canton('Osa', 'Agregando Cantones');
EXEC CREAR_Canton('Golfito', 'Agregando Cantones');
EXEC CREAR_Canton('Coto Brus', 'Agregando Cantones');
EXEC CREAR_Canton('Parrita', 'Agregando Cantones');
EXEC CREAR_Canton('Corredores', 'Agregando Cantones');
EXEC CREAR_Canton('Garabito', 'Agregando Cantones');
EXEC CREAR_Canton('Limón', 'Agregando Cantones');
EXEC CREAR_Canton('Pococí', 'Agregando Cantones');
EXEC CREAR_Canton('Siquirres', 'Agregando Cantones');
EXEC CREAR_Canton('Talamanca', 'Agregando Cantones');
EXEC CREAR_Canton('Matina', 'Agregando Cantones');
EXEC CREAR_Canton('Guácimo', 'Agregando Cantones');
EXEC CREAR_Canton('Belén', 'Agregando Cantones');
EXEC CREAR_Canton('Flores', 'Agregando Cantones');
EXEC CREAR_Canton('San Pablo', 'Agregando Cantones');
EXEC CREAR_Canton('Heredia', 'Agregando Cantones');
EXEC CREAR_Canton('Barva', 'Agregando Cantones');
EXEC CREAR_Canton('Santo Domingo', 'Agregando Cantones');

-- Creacion de provincias
EXEC CREAR_PROVINCIA('San Jose', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Puntarenas', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Limon', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Guanacaste', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Alajuela', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Heredia', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Cartago', 'Agregando Provincia');

--- Creacion de roles
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cliente', 'Clientes', 'Clientes del restaurante', 'Creacion de rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Empleado', 'Empleados', 'Empleados del restaurante', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Gerente', 'Gerentes', 'Gerentes del restaurante', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Gerente_Ventas', 'Gerentes de ventas', 'Gerentes de de ventas', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Mesero', 'Meseros', 'Encargados de tomar pedidos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cocinero', 'Cocineros', 'Encargados de preparar alimentos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Administrador', 'Administradores', 'Administradores generales del sistema', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Recepcionista', 'Recepcionistas', 'Atención al cliente y reservas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cajero', 'Cajeros', 'Encargados del cobro y facturación', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Inventario', 'Encargados de inventario', 'Manejo y control del inventario', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Proveedor', 'Proveedores', 'Proveedores de insumos', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cliente_VIP', 'Clientes VIP', 'Clientes frecuentes con beneficios especiales', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Marketing', 'Departamento de Marketing', 'Encargados de promociones y campañas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Limpieza', 'Encargados de limpieza', 'Responsables del aseo del local', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor', 'Supervisores', 'Supervisión general de operaciones', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Chef', 'Chefs', 'Responsables de la cocina y calidad de platos', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Cocina', 'Asistentes de cocina', 'Ayuda en la preparación de alimentos', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Bartender', 'Bartenders', 'Encargados del área de bebidas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Tecnico', 'Encargados técnicos', 'Soporte técnico y sistemas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Seguridad', 'Personal de seguridad', 'Seguridad del restaurante', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Contador', 'Contadores', 'Manejo de contabilidad y finanzas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Mantenimiento', 'Personal de mantenimiento', 'Reparaciones y mantenimiento general', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Gerencia', 'Asistentes de gerencia', 'Apoyo directo a la gerencia', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Diseñador', 'Diseñadores gráficos', 'Diseño de materiales gráficos y digitales', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('RRHH', 'Recursos Humanos', 'Gestión del talento humano', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Logística', 'Departamento de logística', 'Gestión de logística y distribución', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Eventos', 'Encargados de eventos', 'Coordinación de eventos y actividades', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Auditor', 'Auditores', 'Control interno y auditorías', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Diseñador_Menu', 'Diseñadores de menú', 'Diseño e innovación del menú', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Pasante', 'Pasantes', 'Aprendices en entrenamiento', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Cajero', 'Asistentes de caja', 'Apoyo en el área de caja', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Ayudante_Bar', 'Ayudantes de bar', 'Apoyo al bartender', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Capacitador', 'Capacitadores', 'Capacitación del personal', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Turnos', 'Encargados de turnos', 'Gestión de turnos de trabajo', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Tecnico_Soporte', 'Técnicos de soporte', 'Asistencia técnica básica', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Proveedores', 'Encargados de proveedores', 'Gestión de relaciones con proveedores', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Community_Manager', 'Community Managers', 'Gestión de redes sociales', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Consultor', 'Consultores', 'Asesoramiento externo', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Mesa', 'Encargados de mesa', 'Supervisión del servicio en mesa', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Ayudante_Cocina', 'Ayudantes de cocina', 'Tareas básicas en la cocina', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Analista_Datos', 'Analistas de datos', 'Análisis de información operativa', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Marketing', 'Encargados de marketing', 'Gestión de estrategias de mercado', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Director_General', 'Directores Generales', 'Alta dirección del restaurante', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor_Caja', 'Supervisores de caja', 'Supervisión del área de caja', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Platillos', 'Encargados de platillos', 'Control de calidad de los platillos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Atencion_Cliente', 'Personal de atención al cliente', 'Atención directa a los clientes', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Capitan_Salon', 'Capitanes de salón', 'Coordinación de servicio en salón', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Compras', 'Encargados de compras', 'Gestión de adquisiciones', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor_Limpieza', 'Supervisores de limpieza', 'Supervisión del personal de limpieza', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Administrativo', 'Asistentes administrativos', 'Soporte a las tareas administrativas', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Tester', 'Testers de sistemas', 'Pruebas de software y reportes de errores', 'Creacion del rol', 'Limitado');


SELECT * FROM ROL_PERSONA;
SELECT * FROM CANTON;
SELECT * FROM DISTRITO;
SELECT * FROM PROVINCIA;

--Creacion de personas
EXEC PKT_PERSONAS.CREAR_PERSONA(1184401, 'Johannes', 'Sequeira', '123-456','Gerente', 1, 1, 1, 'js@playacacao.com', 'johannes@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1345667, 'Steven', 'Guerra Fernandez', '222-356','Empleado', 1, 1, 1, 'steven@playacacao.com', 'steven@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1899889, 'Ryan', 'Umana', '222-356','Gerente', 1, 1, 1, 'ryan@playacacao.com', 'ryan@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200345, 'Nidia', 'Infante', '123-456','Cliente', 1, 1, 1, 'nidiaces@gmail.com', 'infante@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200346, 'Carlos', 'Cruz', '231-789','Empleado', 1, 1, 6, 'carlos@playacacao.com', 'ramirez.c@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200347, 'Ana', 'Sánchez', '987-654','Cliente', 63, 113, 81, 'ana@gmail.com', 'sancheza@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200348, 'Luis', 'Castro', '123-111','Mesero', 63, 21, 82, 'luis@playacacao.com', 'castroluis@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200349, 'Elena', 'Vargas', '222-777','Recepcionista', 63, 111, 83, 'elena@playacacao.com', 'vargaselena@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200350, 'Roberto', 'Jiménez', '333-888','Gerente_Ventas', 27, 118, 85, 'roberto@playacacao.com', 'jimenezr@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200351, 'Diana', 'Alfaro', '444-999','Cocinero', 27, 109, 85, 'diana@playacacao.com', 'alfarodiana@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200352, 'Jorge', 'Mariz', '111-222','Cliente', 27, 82, 86, 'jorge@gmail.com', 'camachoj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200353, 'Laura', 'Araya', '555-666','Cliente_VIP', 26, 84, 87, 'laura@gmail.com', 'chaconl@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200354, 'Andrés', 'Vega', '777-888','Encargado_Inventario', 26, 108, 88, 'andres@playacacao.com', 'vegandres@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200355, 'María', 'Esquivel', '101-202','Empleado', 26, 1, 89, 'maria@playacacao.com', 'esquivelm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200356, 'Ricardo', 'Cordero', '303-404','Chef', 21, 107, 90, 'ricardo@playacacao.com', 'corderor@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200357, 'Patricia', 'Salazar', '505-606','Asistente_Cocina', 21, 106, 91, 'patricia@playacacao.com', 'salazarp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200358, 'Ernesto', 'Valverde', '707-808','Cajero', 21, 105, 92, 'ernesto@playacacao.com', 'valverdee@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200359, 'Gloria', 'Navarro', '909-010','Cliente', 21, 104, 93, 'gloria@gmail.com', 'navarrog@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200360, 'Daniel', 'Solís', '112-113','Bartender', 21, 85, 94, 'daniel@playacacao.com', 'solisd@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200361, 'Isabel', 'Carvajal', '114-115','Encargado_Tecnico', 24, 86, 95, 'isabel@playacacao.com', 'carvajali@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200362, 'Oscar', 'Marín', '116-117','Seguridad', 24, 87, 96, 'oscar@playacacao.com', 'marino@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200363, 'Lucía', 'Barrantes', '118-119','Marketing', 24, 88, 97, 'lucia@playacacao.com', 'barrantesl@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200364, 'Mauricio', 'Campos', '120-121','Administrador', 24, 89, 98, 'mauricio@playacacao.com', 'camposm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200365, 'Pamela', 'Ruiz', '122-123','Encargado_Eventos', 24, 90, 99, 'pamela@playacacao.com', 'ruizp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200366, 'Sebastián', 'Lobo', '124-125','Contador', 24, 91, 100, 'sebastian@playacacao.com', 'lobose@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200367, 'Jimena', 'Zamora', '126-127','Ayudante_Cocina', 24, 92, 101, 'jimena@playacacao.com', 'zamoraj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200368, 'Esteban', 'Picado', '128-129','Asistente_Gerencia', 24, 102,'esteban@playacacao.com', 'picadoe@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200369, 'Adriana', 'Fonseca', '130-131','Consultor', 24, 94, 103, 'adriana@playacacao.com', 'fonsecaa@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200370, 'Julián', 'Artavia', '132-133','Mantenimiento', 25, 95, 104, 'julian@playacacao.com', 'artaviaj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200371, 'Maricela', 'Rojas', '134-135','Community_Manager', 25, 96, 105, 'maricela@playacacao.com', 'rojasm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200372, 'Pablo', 'González', '136-137','Encargado_Proveedores', 25, 97, 106, 'pablo@playacacao.com', 'gonzalezp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200373, 'Tatiana', 'Leiva', '138-139','Tester', 25, 98, 108, 'tatiana@playacacao.com', 'leivat@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200374, 'Rodrigo', 'Calderón', '140-141','Supervisor', 25, 99, 109, 'rodrigo@playacacao.com', 'calderonr@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200375, 'Silvia', 'López', '142-143','Encargado_Compras', 63, 100, 119, 'silvia@playacacao.com', 'lopezs@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(777777, 'InvalidUser', 'InvalidUser', '00000','Cliente', 1, 1, 1, 'Invalid', 'Invalid','Invalid','Agregando personas');

--Creacion de puestos
EXEC PKG_PUESTOS.CREAR_PUESTO('Mesero', 300000, 'Mesero del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Cajero', 600000, 'Cajero del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Gerente', 900000, 'Gerente general del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Chef Ejecutivo', 1200000, 'Encargado principal de la cocina', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Sous Chef', 950000, 'Segundo al mando en cocina', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Cocinero', 500000, 'Cocinero general del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Ayudante de Cocina', 400000, 'Asistente en cocina', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Bartender', 450000, 'Preparación y servicio de bebidas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Recepcionista', 450000, 'Atención de clientes en recepción', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Administrador', 850000, 'Encargado de operaciones administrativas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Inventario', 550000, 'Gestión de inventario y suministros', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Limpieza', 300000, 'Mantenimiento de limpieza general', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Eventos', 700000, 'Coordinación de eventos especiales', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Community Manager', 600000, 'Manejo de redes sociales del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Marketing', 650000, 'Responsable de estrategias publicitarias', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Supervisor de Turno', 700000, 'Supervisión operativa por turno', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Gerente de Ventas', 950000, 'Encargado de ventas y promociones', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Mantenimiento General', 400000, 'Reparaciones y mantenimiento básico', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Personal de Seguridad', 450000, 'Seguridad del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Contador', 900000, 'Encargado contable y financiero', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Asistente Administrativo', 550000, 'Soporte administrativo', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Compras', 650000, 'Responsable de adquisición de insumos', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Diseñador Gráfico', 600000, 'Diseño de material visual y gráfico', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Proveedores', 600000, 'Gestión y contacto con proveedores', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Asistente de Gerencia', 700000, 'Asistencia directa a la gerencia', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Consultor Externo', 1100000, 'Consultoría especializada en operaciones', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Hostess', 400000, 'Recibir y acomodar clientes', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Runner', 320000, 'Entrega de platos desde cocina a mesas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Tecnología', 800000, 'Gestión de infraestructura tecnológica', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Analista de Datos', 750000, 'Análisis de datos de operación y ventas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Capacitación', 650000, 'Formación del personal', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Calidad', 700000, 'Supervisión de estándares de calidad', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Reservaciones', 500000, 'Manejo de sistema de reservas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Operador Telefónico', 400000, 'Atención de llamadas telefónicas', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Lavaplatos', 300000, 'Encargado de limpieza de utensilios de cocina', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Ayudante de Bodega', 350000, 'Apoyo en logística y almacenamiento', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Diseñador UX/UI', 750000, 'Diseño de interfaz de usuario', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Tester de Sistemas', 700000, 'Pruebas de software y calidad', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Logística', 700000, 'Coordinación de entregas y abastecimiento', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Nómina', 850000, 'Manejo de planillas y pagos', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Supervisor de Cocina', 750000, 'Supervisión del personal de cocina', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Relaciones Públicas', 800000, 'Manejo de imagen y relaciones institucionales', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Atención al Cliente', 650000, 'Gestión de experiencia del cliente', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Fotógrafo de Productos', 500000, 'Fotografía de menú y productos', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Programador Web', 850000, 'Desarrollo del sitio web del restaurante', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Seguridad Alimentaria', 700000, 'Vigilancia de normas de higiene y seguridad', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Capacitador de Personal', 600000, 'Capacitación continua del equipo', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Proyectos', 950000, 'Gestión de proyectos estratégicos', 'Agregando puesto');
EXEC PKG_PUESTOS.CREAR_PUESTO('Encargado de Delivery', 500000, 'Coordinación de pedidos a domicilio', 'Agregando puesto');


--Creacion de departamentos
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Gerenncia','Departamento administrativo', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Saloneria','Departamento de salon', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Cocina','Departamento de cocina', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Caja', 'Departamento de caja y cobros', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Bar', 'Departamento de bar y bebidas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Limpieza', 'Departamento de limpieza y mantenimiento', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Recursos Humanos', 'Departamento de gestión del personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Mantenimiento', 'Departamento de mantenimiento general', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Marketing', 'Departamento de publicidad y redes', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Inventario', 'Departamento de control de inventario', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Eventos', 'Departamento de organización de eventos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Compras', 'Departamento de compras e insumos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Contabilidad', 'Departamento financiero y contable', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('TI', 'Departamento de tecnología e infraestructura', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Seguridad', 'Departamento de seguridad', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Atención al Cliente', 'Departamento de servicio al cliente', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Reservaciones', 'Departamento de reservas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Calidad', 'Departamento de aseguramiento de calidad', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Capacitación', 'Departamento de formación de personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Logística', 'Departamento de logística y distribución', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Ventas', 'Departamento de ventas y promociones', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Públicas', 'Departamento de comunicación y RP', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Diseño', 'Departamento de diseño gráfico y visual', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Legal', 'Departamento legal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Consultoría', 'Departamento de asesoría externa', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Producción', 'Departamento de producción de alimentos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Distribución', 'Departamento de reparto y entrega', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Laborales', 'Departamento de relaciones internas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Facturación', 'Departamento de facturación', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Soporte Técnico', 'Departamento de soporte TI', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Gestión de Proyectos', 'Departamento de planificación de proyectos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Decoración', 'Departamento de ambientación del local', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Servicio Express', 'Departamento de entregas rápidas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Prensa', 'Departamento de medios y comunicación', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Redes Sociales', 'Departamento de gestión de redes', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Desarrollo', 'Departamento de innovación y desarrollo', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Análisis de Datos', 'Departamento de análisis estadístico', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Control Interno', 'Departamento de auditoría y control', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Ingeniería de Procesos', 'Departamento de mejora de procesos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Sostenibilidad', 'Departamento de responsabilidad ambiental', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Internacionales', 'Departamento de cooperación externa', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Publicidad', 'Departamento de campañas publicitarias', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Administración de Personal', 'Departamento de manejo de personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Tráfico', 'Departamento de coordinación interna', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Call Center', 'Departamento de atención telefónica', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Archivo', 'Departamento de gestión documental', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Proyectos Especiales', 'Departamento de proyectos estratégicos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Innovación', 'Departamento de mejora continua', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Transporte', 'Departamento de movilidad y transporte', 'Agregando Departamento');


--Creacion de empleados
EXEC CREAR_EMPLEADO(10001,1,1,1000000,1184401,'Agregando Empleado');

--Agregar platillos
EXEC PKT_PLATILLOS.CREAR_PLATILLO('Arroz con camarones', 5000, 50, 'Agregando platillos');
EXEC CREAR_PLATILLO('Papas fritas', 2000, 100, 'Agregando platillos');
EXEC CREAR_PLATILLO('Dedos de pollo', 3000, 80, 'Agregando platillos');
EXEC CREAR_PLATILLO('Arroz con Pollo', 3500, 120, 'Platillo típico costarricense');
EXEC CREAR_PLATILLO('Casado con Carne', 4000, 110, 'Incluye arroz, frijoles, carne de res');
EXEC CREAR_PLATILLO('Ensalada César con Pollo', 3200, 90, 'Fresca y ligera');
EXEC CREAR_PLATILLO('Pizza Margarita', 4500, 80, 'Base de tomate, albahaca y mozzarella');
EXEC CREAR_PLATILLO('Pasta Alfredo', 4700, 75, 'Salsa cremosa con champiñones');
EXEC CREAR_PLATILLO('Ceviche Mixto', 5000, 65, 'Con camarón y pescado blanco');
EXEC CREAR_PLATILLO('Hamburguesa Clásica', 3800, 100, 'Pan artesanal con carne de res');
EXEC CREAR_PLATILLO('Chifrijo', 4200, 95, 'Frijoles, chicharrón y pico de gallo');
EXEC CREAR_PLATILLO('Tacos al Pastor', 4300, 70, 'Con piña, cebolla y cilantro');
EXEC CREAR_PLATILLO('Sopa Negra', 3000, 85, 'Frijoles negros con huevo duro');
EXEC CREAR_PLATILLO('Quesadillas de Pollo', 3900, 95, 'Tortilla rellena de queso y pollo');
EXEC CREAR_PLATILLO('Arroz Chaufa', 4600, 80, 'Fusión peruana-china con vegetales');
EXEC CREAR_PLATILLO('Filete de Pescado', 5200, 60, 'A la plancha con vegetales');
EXEC CREAR_PLATILLO('Gallo Pinto', 2800, 120, 'Tradicional desayuno tico');
EXEC CREAR_PLATILLO('Panqueques con Miel', 3100, 100, 'Desayuno dulce');
EXEC CREAR_PLATILLO('Burrito de Res', 4100, 90, 'Con frijoles y guacamole');
EXEC CREAR_PLATILLO('Arepas Rellenas', 3500, 85, 'Con carne mechada');
EXEC CREAR_PLATILLO('Pollo Empanizado', 3900, 95, 'Con papas fritas');
EXEC CREAR_PLATILLO('Chow Mein', 4500, 70, 'Fideos salteados estilo chino');
EXEC CREAR_PLATILLO('Crema de Ayote', 3100, 100, 'Sopa cremosa de ayote');
EXEC CREAR_PLATILLO('Tamal Asado', 3200, 75, 'Hecho con masa de maíz y relleno');
EXEC CREAR_PLATILLO('Tortilla Española', 3600, 80, 'Con papa y huevo');
EXEC CREAR_PLATILLO('Empanadas de Frijol', 2900, 95, 'Masa frita con relleno salado');
EXEC CREAR_PLATILLO('Croquetas de Pollo', 3500, 90, 'Crujientes por fuera, suaves por dentro');
EXEC CREAR_PLATILLO('Hamburguesa Vegana', 4000, 70, 'Con torta de garbanzo');
EXEC CREAR_PLATILLO('Pasta al Pesto', 4700, 85, 'Salsa de albahaca y ajo');
EXEC CREAR_PLATILLO('Crepes Dulces', 3100, 80, 'Con nutella y fruta');
EXEC CREAR_PLATILLO('Lasaña de Carne', 4900, 70, 'Capas de pasta, carne y queso');
EXEC CREAR_PLATILLO('Tarta de Queso', 3500, 100, 'Postre frío');
EXEC CREAR_PLATILLO('Canelones de Espinaca', 3700, 75, 'Rellenos vegetarianos');
EXEC CREAR_PLATILLO('Rollos Primavera', 3300, 90, 'Con salsa agridulce');
EXEC CREAR_PLATILLO('Pollo Teriyaki', 4800, 65, 'Estilo japonés');
EXEC CREAR_PLATILLO('Alitas BBQ', 4200, 95, 'Picantes o dulces');
EXEC CREAR_PLATILLO('Cazuela de Mariscos', 5500, 60, 'Con crema y vino blanco');
EXEC CREAR_PLATILLO('Pupusas Revueltas', 3600, 90, 'Queso, frijol y chicharrón');
EXEC CREAR_PLATILLO('Sushi Roll California', 5000, 70, 'Aguacate y surimi');
EXEC CREAR_PLATILLO('Fajitas Mixtas', 4600, 85, 'Res y pollo con vegetales');
EXEC CREAR_PLATILLO('Bistec Encebollado', 4400, 80, 'Clásico costarricense');
EXEC CREAR_PLATILLO('Sándwich Cubano', 4000, 100, 'Con jamón y pepinillo');
EXEC CREAR_PLATILLO('Pizza Hawaiana', 4700, 85, 'Con piña y jamón');
EXEC CREAR_PLATILLO('Cremas Heladas', 3000, 90, 'Diferentes sabores');
EXEC CREAR_PLATILLO('Costillas BBQ', 5600, 70, 'Jugosas y bien cocidas');
EXEC CREAR_PLATILLO('Ensalada de Atún', 3400, 100, 'Fresca con vinagreta');
EXEC CREAR_PLATILLO('Galletas con Helado', 3200, 95, 'Postre muy solicitado');
EXEC CREAR_PLATILLO('Milkshake de Chocolate', 3300, 90, 'Refrescante y dulce');
EXEC CREAR_PLATILLO('Panini de Pollo', 3900, 80, 'Tostado con queso');
EXEC CREAR_PLATILLO('Torta Chilena', 3700, 85, 'Postre tradicional');
EXEC CREAR_PLATILLO('Café Cappuccino', 2800, 120, 'Perfecto para la tarde');
EXEC CREAR_PLATILLO('Brownie con Helado', 3600, 90, 'Combinación perfecta');

-- Agregar menús
EXEC CREAR_MENU('Menu Vegetariano', 'Opciones sin carne, frescas y saludables', 'Agregando menus');
EXEC CREAR_MENU('Menu Vegano', 'Completamente libre de productos animales', 'Agregando menus');
EXEC CREAR_MENU('Menu Sin Gluten', 'Especial para personas con intolerancia al gluten', 'Agregando menus');
EXEC CREAR_MENU('Menu del Día', 'Platos variados que cambian diariamente', 'Agregando menus');
EXEC CREAR_MENU('Menu Desayuno', 'Variedad de desayunos típicos e internacionales', 'Agregando menus');
EXEC CREAR_MENU('Menu Almuerzo', 'Comidas fuertes y balanceadas para el mediodía', 'Agregando menus');
EXEC CREAR_MENU('Menu Cena', 'Opciones ligeras y sabrosas para la noche', 'Agregando menus');
EXEC CREAR_MENU('Menu de Mariscos', 'Especialidades del mar', 'Agregando menus');
EXEC CREAR_MENU('Menu Tico', 'Platos tradicionales costarricenses', 'Agregando menus');
EXEC CREAR_MENU('Menu Mexicano', 'Tacos, enchiladas y más delicias mexicanas', 'Agregando menus');
EXEC CREAR_MENU('Menu Italiano', 'Pastas, pizzas y sabores italianos clásicos', 'Agregando menus');
EXEC CREAR_MENU('Menu Asiático', 'Cocina oriental con toques locales', 'Agregando menus');
EXEC CREAR_MENU('Menu Parrilla', 'Carnes a la parrilla y guarniciones', 'Agregando menus');
EXEC CREAR_MENU('Menu Light', 'Platos bajos en calorías y grasas', 'Agregando menus');
EXEC CREAR_MENU('Menu Gourmet', 'Alta cocina para paladares exigentes', 'Agregando menus');
EXEC CREAR_MENU('Menu Rápido', 'Comidas rápidas para llevar', 'Agregando menus');
EXEC CREAR_MENU('Menu Fiestas', 'Menú especial para celebraciones y eventos', 'Agregando menus');
EXEC CREAR_MENU('Menu Navidad', 'Especial de temporada navideña', 'Agregando menus');
EXEC CREAR_MENU('Menu Fin de Año', 'Cierre del año con sabores especiales', 'Agregando menus');
EXEC CREAR_MENU('Menu San Valentín', 'Para una velada romántica', 'Agregando menus');
EXEC CREAR_MENU('Menu Halloween', 'Comidas temáticas para celebrar', 'Agregando menus');
EXEC CREAR_MENU('Menu Pascua', 'Opciones especiales para Semana Santa', 'Agregando menus');
EXEC CREAR_MENU('Menu de Sopas', 'Sopas tradicionales e internacionales', 'Agregando menus');
EXEC CREAR_MENU('Menu de Postres', 'Deliciosos postres caseros', 'Agregando menus');
EXEC CREAR_MENU('Menu Bebidas', 'Jugos, cócteles y refrescos', 'Agregando menus');
EXEC CREAR_MENU('Menu Café', 'Café y acompañamientos dulces', 'Agregando menus');
EXEC CREAR_MENU('Menu Internacional', 'Selección de platos de varios países', 'Agregando menus');
EXEC CREAR_MENU('Menu Premium', 'Platos exclusivos y selectos', 'Agregando menus');
EXEC CREAR_MENU('Menu BBQ', 'Costillas, hamburguesas y parrilla americana', 'Agregando menus');
EXEC CREAR_MENU('Menu Mediterráneo', 'Sabores del mar Mediterráneo', 'Agregando menus');
EXEC CREAR_MENU('Menu Saludable', 'Comida nutritiva y balanceada', 'Agregando menus');
EXEC CREAR_MENU('Menu Keto', 'Opciones bajas en carbohidratos', 'Agregando menus');
EXEC CREAR_MENU('Menu Proteico', 'Alto contenido en proteínas', 'Agregando menus');
EXEC CREAR_MENU('Menu Deportivo', 'Energía y recuperación para atletas', 'Agregando menus');
EXEC CREAR_MENU('Menu Picante', 'Para los que aman el fuego en la boca', 'Agregando menus');
EXEC CREAR_MENU('Menu Oriental', 'Fusión de sabores de Asia oriental', 'Agregando menus');
EXEC CREAR_MENU('Menu Caribeño', 'Cocina del Caribe con coco, pescado y más', 'Agregando menus');
EXEC CREAR_MENU('Menu Infantil Saludable', 'Comida divertida y nutritiva para niños', 'Agregando menus');
EXEC CREAR_MENU('Menu Económico', 'Platos sabrosos a bajo costo', 'Agregando menus');
EXEC CREAR_MENU('Menu Clásico', 'Recetas tradicionales que nunca fallan', 'Agregando menus');
EXEC CREAR_MENU('Menu Sorpresa', 'Chef’s choice para los aventureros', 'Agregando menus');
EXEC CREAR_MENU('Menu Temporada', 'Basado en ingredientes frescos del momento', 'Agregando menus');
EXEC CREAR_MENU('Menu Buffet', 'Opción libre con variedad de platillos', 'Agregando menus');
EXEC CREAR_MENU('Menu Brunch', 'Entre desayuno y almuerzo, ideal para el fin de semana', 'Agregando menus');
EXEC CREAR_MENU('Menu Romántico', 'Perfecto para una cena en pareja', 'Agregando menus');
EXEC CREAR_MENU('Menu Degustación', 'Muestras pequeñas de muchos sabores', 'Agregando menus');
EXEC CREAR_MENU('Menu Fusión', 'Combinación de distintas cocinas del mundo', 'Agregando menus');

--Agregar platillos al menu
EXEC CREAR_PLATILLO_MENU(21,1,'Agregando platillos al menu');

--Agregar pedidos
EXEC CREAR_PEDIDO(10001,10000,'Nuevo','Agregando_Pedido');

--Agregamos metodos de pago
EXEC CREAR_METODO_DE_PAGO('Tarjeta','Pago con tarjeta de debito o credito', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Tarjeta de Credito','Pago mediante tarjeta de credito bancaria.', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Efectivo','Pago con efectivo o sinpe', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Cheque','Pago con cheque', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Puntos','Pago con puntos del restaurante', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Tasa 0','Pago con tasa 0 del banco', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Sinpe movil','Pago con sinpemovil', 'Agregando Metodo de pago');

--Agregamos platillos a un pedido
EXEC CREAR_ENTRADA_LISTA_PLATILLOS(2,2,'Agregando pedidos al pedido 1');
EXEC CREAR_ENTRADA_LISTA_PLATILLOS(1,2,'Agregando pedidos al pedido 1');

--Agregamos una factura
EXEC CREAR_FACTURA(2,1,0,'Agregando Factura');