---------------------- Correr en session de Playa Cacao---------------------
/*
Setup inicial de la base de datos, crea el usuario de administrador de la pagina web asi como una cantidad de entradas para empezar a trabajar con la pagina web
*/

EXEC CREAR_DISTRITO('San Antonio', 'Agregando distritos');
EXEC CREAR_DISTRITO('Zapoote', 'Agregando distritos');
EXEC CREAR_DISTRITO('Desamparados', 'Agregando distritos');
EXEC CREAR_DISTRITO('Merced', 'Agregando distritos');
EXEC CREAR_DISTRITO('Hospital', 'Agregando distritos');
EXEC CREAR_DISTRITO('Catedral', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Francisco', 'Agregando distritos');
EXEC CREAR_DISTRITO('Carrizal', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Isidro', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Sebastián', 'Agregando distritos');
EXEC CREAR_DISTRITO('Hatillo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Gravilias', 'Agregando distritos');
EXEC CREAR_DISTRITO('Pavas', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Uruca', 'Agregando distritos');
EXEC CREAR_DISTRITO('Mata Redonda', 'Agregando distritos');
EXEC CREAR_DISTRITO('Zapote', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Juan de Dios', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael Abajo', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael Arriba', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Miguel', 'Agregando distritos');
EXEC CREAR_DISTRITO('Los Guido', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Pedro', 'Agregando distritos');
EXEC CREAR_DISTRITO('Sabanilla', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Vicente', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guadalupe', 'Agregando distritos');
EXEC CREAR_DISTRITO('Ipís', 'Agregando distritos');
EXEC CREAR_DISTRITO('Rancho Redondo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Calle Blancos', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Juan', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Diego', 'Agregando distritos');
EXEC CREAR_DISTRITO('Tres Ríos', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Rafael', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Pablo', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santa Rosa', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santiago', 'Agregando distritos');
EXEC CREAR_DISTRITO('Santa Cruz', 'Agregando distritos');
EXEC CREAR_DISTRITO('Paraíso', 'Agregando distritos');
EXEC CREAR_DISTRITO('Orosi', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cachí', 'Agregando distritos');
EXEC CREAR_DISTRITO('Birrisito', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Carlos', 'Agregando distritos');
EXEC CREAR_DISTRITO('Florencia', 'Agregando distritos');
EXEC CREAR_DISTRITO('Quesada', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cutris', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Fortuna', 'Agregando distritos');
EXEC CREAR_DISTRITO('Venado', 'Agregando distritos');
EXEC CREAR_DISTRITO('La Tigra', 'Agregando distritos');
EXEC CREAR_DISTRITO('Monterrey', 'Agregando distritos');
EXEC CREAR_DISTRITO('Pital', 'Agregando distritos');
EXEC CREAR_DISTRITO('Aguas Zarcas', 'Agregando distritos');
EXEC CREAR_DISTRITO('San Isidro de Peñas Blancas', 'Agregando distritos');
EXEC CREAR_DISTRITO('Limón', 'Agregando distritos');
EXEC CREAR_DISTRITO('Valle La Estrella', 'Agregando distritos');
EXEC CREAR_DISTRITO('Matama', 'Agregando distritos');
EXEC CREAR_DISTRITO('Roxana', 'Agregando distritos');
EXEC CREAR_DISTRITO('Cariari', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guápiles', 'Agregando distritos');
EXEC CREAR_DISTRITO('Jiménez', 'Agregando distritos');
EXEC CREAR_DISTRITO('Reventazón', 'Agregando distritos');
EXEC CREAR_DISTRITO('Guácimo', 'Agregando distritos');

-- Creacion de Cantones
EXEC CREAR_Canton('Pérez Zeledón', 'Agregando Cantones');
EXEC CREAR_Canton('Escazú', 'Agregando Cantones');
EXEC CREAR_Canton('Moravia', 'Agregando Cantones');
EXEC CREAR_Canton('Alajuela', 'Agregando Cantones');
EXEC CREAR_Canton('San Ramón', 'Agregando Cantones');
EXEC CREAR_Canton('Grecia', 'Agregando Cantones');
EXEC CREAR_Canton('Atenas', 'Agregando Cantones');
EXEC CREAR_Canton('San Mateo', 'Agregando Cantones');
EXEC CREAR_Canton('Palmares', 'Agregando Cantones');
EXEC CREAR_Canton('Poás', 'Agregando Cantones');
EXEC CREAR_Canton('Orotina', 'Agregando Cantones');
EXEC CREAR_Canton('Desamparados', 'Agregando Cantones');
EXEC CREAR_Canton('Acosta', 'Agregando Cantones');
EXEC CREAR_Canton('Aserrí', 'Agregando Cantones');
EXEC CREAR_Canton('Curridabat', 'Agregando Cantones');
EXEC CREAR_Canton('Goicoechea', 'Agregando Cantones');
EXEC CREAR_Canton('Montes de Oca', 'Agregando Cantones');
EXEC CREAR_Canton('Tibás', 'Agregando Cantones');
EXEC CREAR_Canton('Santa Ana', 'Agregando Cantones');
EXEC CREAR_Canton('Alajuelita', 'Agregando Cantones');
EXEC CREAR_Canton('Vásquez de Coronado', 'Agregando Cantones');
EXEC CREAR_Canton('Puriscal', 'Agregando Cantones');
EXEC CREAR_Canton('Turrubares', 'Agregando Cantones');
EXEC CREAR_Canton('Dota', 'Agregando Cantones');
EXEC CREAR_Canton('Tarrazú', 'Agregando Cantones');
EXEC CREAR_Canton('León Cortés', 'Agregando Cantones');
EXEC CREAR_Canton('Cartago', 'Agregando Cantones');
EXEC CREAR_Canton('Paraíso', 'Agregando Cantones');
EXEC CREAR_Canton('La Unión', 'Agregando Cantones');
EXEC CREAR_Canton('Jiménez', 'Agregando Cantones');
EXEC CREAR_Canton('Turrialba', 'Agregando Cantones');
EXEC CREAR_Canton('Alvarado', 'Agregando Cantones');
EXEC CREAR_Canton('Oreamuno', 'Agregando Cantones');
EXEC CREAR_Canton('El Guarco', 'Agregando Cantones');
EXEC CREAR_Canton('San Carlos', 'Agregando Cantones');
EXEC CREAR_Canton('Zarcero', 'Agregando Cantones');
EXEC CREAR_Canton('Sarchí', 'Agregando Cantones');
EXEC CREAR_Canton('Upala', 'Agregando Cantones');
EXEC CREAR_Canton('Los Chiles', 'Agregando Cantones');
EXEC CREAR_Canton('Guatuso', 'Agregando Cantones');
EXEC CREAR_Canton('Puntarenas', 'Agregando Cantones');
EXEC CREAR_Canton('Esparza', 'Agregando Cantones');
EXEC CREAR_Canton('Buenos Aires', 'Agregando Cantones');
EXEC CREAR_Canton('Montes de Oro', 'Agregando Cantones');
EXEC CREAR_Canton('Osa', 'Agregando Cantones');
EXEC CREAR_Canton('Golfito', 'Agregando Cantones');
EXEC CREAR_Canton('Coto Brus', 'Agregando Cantones');
EXEC CREAR_Canton('Parrita', 'Agregando Cantones');
EXEC CREAR_Canton('Corredores', 'Agregando Cantones');
EXEC CREAR_Canton('Garabito', 'Agregando Cantones');
EXEC CREAR_Canton('Limón', 'Agregando Cantones');
EXEC CREAR_Canton('Pococí', 'Agregando Cantones');
EXEC CREAR_Canton('Siquirres', 'Agregando Cantones');
EXEC CREAR_Canton('Talamanca', 'Agregando Cantones');
EXEC CREAR_Canton('Matina', 'Agregando Cantones');
EXEC CREAR_Canton('Guácimo', 'Agregando Cantones');
EXEC CREAR_Canton('Belén', 'Agregando Cantones');
EXEC CREAR_Canton('Flores', 'Agregando Cantones');
EXEC CREAR_Canton('San Pablo', 'Agregando Cantones');
EXEC CREAR_Canton('Heredia', 'Agregando Cantones');
EXEC CREAR_Canton('Barva', 'Agregando Cantones');
EXEC CREAR_Canton('Santo Domingo', 'Agregando Cantones');

-- Creacion de provincias
EXEC CREAR_PROVINCIA('San Jose', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Puntarenas', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Limon', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Guanacaste', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Alajuela', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Heredia', 'Agregando Provincia');
EXEC CREAR_PROVINCIA('Cartago', 'Agregando Provincia');

--- Creacion de roles
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cliente', 'Clientes', 'Clientes del restaurante', 'Creacion de rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Empleado', 'Empleados', 'Empleados del restaurante', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Gerente', 'Gerentes', 'Gerentes del restaurante', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Gerente_Ventas', 'Gerentes de ventas', 'Gerentes de de ventas', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Mesero', 'Meseros', 'Encargados de tomar pedidos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cocinero', 'Cocineros', 'Encargados de preparar alimentos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Administrador', 'Administradores', 'Administradores generales del sistema', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Recepcionista', 'Recepcionistas', 'Atención al cliente y reservas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cajero', 'Cajeros', 'Encargados del cobro y facturación', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Inventario', 'Encargados de inventario', 'Manejo y control del inventario', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Proveedor', 'Proveedores', 'Proveedores de insumos', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Cliente_VIP', 'Clientes VIP', 'Clientes frecuentes con beneficios especiales', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Marketing', 'Departamento de Marketing', 'Encargados de promociones y campañas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Limpieza', 'Encargados de limpieza', 'Responsables del aseo del local', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor', 'Supervisores', 'Supervisión general de operaciones', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Chef', 'Chefs', 'Responsables de la cocina y calidad de platos', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Cocina', 'Asistentes de cocina', 'Ayuda en la preparación de alimentos', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Bartender', 'Bartenders', 'Encargados del área de bebidas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Tecnico', 'Encargados técnicos', 'Soporte técnico y sistemas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Seguridad', 'Personal de seguridad', 'Seguridad del restaurante', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Contador', 'Contadores', 'Manejo de contabilidad y finanzas', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Mantenimiento', 'Personal de mantenimiento', 'Reparaciones y mantenimiento general', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Gerencia', 'Asistentes de gerencia', 'Apoyo directo a la gerencia', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Diseñador', 'Diseñadores gráficos', 'Diseño de materiales gráficos y digitales', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('RRHH', 'Recursos Humanos', 'Gestión del talento humano', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Logística', 'Departamento de logística', 'Gestión de logística y distribución', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Eventos', 'Encargados de eventos', 'Coordinación de eventos y actividades', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Auditor', 'Auditores', 'Control interno y auditorías', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Diseñador_Menu', 'Diseñadores de menú', 'Diseño e innovación del menú', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Pasante', 'Pasantes', 'Aprendices en entrenamiento', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Cajero', 'Asistentes de caja', 'Apoyo en el área de caja', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Ayudante_Bar', 'Ayudantes de bar', 'Apoyo al bartender', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Capacitador', 'Capacitadores', 'Capacitación del personal', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Turnos', 'Encargados de turnos', 'Gestión de turnos de trabajo', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Tecnico_Soporte', 'Técnicos de soporte', 'Asistencia técnica básica', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Proveedores', 'Encargados de proveedores', 'Gestión de relaciones con proveedores', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Community_Manager', 'Community Managers', 'Gestión de redes sociales', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Consultor', 'Consultores', 'Asesoramiento externo', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Mesa', 'Encargados de mesa', 'Supervisión del servicio en mesa', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Ayudante_Cocina', 'Ayudantes de cocina', 'Tareas básicas en la cocina', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Analista_Datos', 'Analistas de datos', 'Análisis de información operativa', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Marketing', 'Encargados de marketing', 'Gestión de estrategias de mercado', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Director_General', 'Directores Generales', 'Alta dirección del restaurante', 'Creacion del rol', 'Completo');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor_Caja', 'Supervisores de caja', 'Supervisión del área de caja', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Platillos', 'Encargados de platillos', 'Control de calidad de los platillos', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Atencion_Cliente', 'Personal de atención al cliente', 'Atención directa a los clientes', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Capitan_Salon', 'Capitanes de salón', 'Coordinación de servicio en salón', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Encargado_Compras', 'Encargados de compras', 'Gestión de adquisiciones', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Supervisor_Limpieza', 'Supervisores de limpieza', 'Supervisión del personal de limpieza', 'Creacion del rol', 'Parcial');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Asistente_Administrativo', 'Asistentes administrativos', 'Soporte a las tareas administrativas', 'Creacion del rol', 'Limitado');
EXEC PKT_ROL_PERSONA.CREAR_ROL_PERSONA('Tester', 'Testers de sistemas', 'Pruebas de software y reportes de errores', 'Creacion del rol', 'Limitado');


SELECT * FROM ROL_PERSONA;
SELECT * FROM CANTON;
SELECT * FROM DISTRITO;
SELECT * FROM PROVINCIA;

--Creacion de personas
EXEC PKT_PERSONAS.CREAR_PERSONA(1184401, 'Johannes', 'Sequeira', '123-456','Gerente', 1, 1, 1, 'js@playacacao.com', 'johannes@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1345667, 'Steven', 'Guerra Fernandez', '222-356','Empleado', 1, 1, 1, 'steven@playacacao.com', 'steven@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1899889, 'Ryan', 'Umana', '222-356','Gerente', 1, 1, 1, 'ryan@playacacao.com', 'ryan@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200345, 'Nidia', 'Infante', '123-456','Cliente', 1, 1, 1, 'nidiaces@gmail.com', 'infante@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200346, 'Carlos', 'Cruz', '231-789','Empleado', 1, 1, 6, 'carlos@playacacao.com', 'ramirez.c@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200347, 'Ana', 'Sánchez', '987-654','Cliente', 63, 113, 81, 'ana@gmail.com', 'sancheza@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200348, 'Luis', 'Castro', '123-111','Mesero', 63, 21, 82, 'luis@playacacao.com', 'castroluis@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200349, 'Elena', 'Vargas', '222-777','Recepcionista', 63, 111, 83, 'elena@playacacao.com', 'vargaselena@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200350, 'Roberto', 'Jiménez', '333-888','Gerente_Ventas', 27, 118, 85, 'roberto@playacacao.com', 'jimenezr@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200351, 'Diana', 'Alfaro', '444-999','Cocinero', 27, 109, 85, 'diana@playacacao.com', 'alfarodiana@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200352, 'Jorge', 'Mariz', '111-222','Cliente', 27, 82, 86, 'jorge@gmail.com', 'camachoj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200353, 'Laura', 'Araya', '555-666','Cliente_VIP', 26, 84, 87, 'laura@gmail.com', 'chaconl@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200354, 'Andrés', 'Vega', '777-888','Encargado_Inventario', 26, 108, 88, 'andres@playacacao.com', 'vegandres@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200355, 'María', 'Esquivel', '101-202','Empleado', 26, 1, 89, 'maria@playacacao.com', 'esquivelm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200356, 'Ricardo', 'Cordero', '303-404','Chef', 21, 107, 90, 'ricardo@playacacao.com', 'corderor@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200357, 'Patricia', 'Salazar', '505-606','Asistente_Cocina', 21, 106, 91, 'patricia@playacacao.com', 'salazarp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200358, 'Ernesto', 'Valverde', '707-808','Cajero', 21, 105, 92, 'ernesto@playacacao.com', 'valverdee@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200359, 'Gloria', 'Navarro', '909-010','Cliente', 21, 104, 93, 'gloria@gmail.com', 'navarrog@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200360, 'Daniel', 'Solís', '112-113','Bartender', 21, 85, 94, 'daniel@playacacao.com', 'solisd@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200361, 'Isabel', 'Carvajal', '114-115','Encargado_Tecnico', 24, 86, 95, 'isabel@playacacao.com', 'carvajali@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200362, 'Oscar', 'Marín', '116-117','Seguridad', 24, 87, 96, 'oscar@playacacao.com', 'marino@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200363, 'Lucía', 'Barrantes', '118-119','Marketing', 24, 88, 97, 'lucia@playacacao.com', 'barrantesl@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200364, 'Mauricio', 'Campos', '120-121','Administrador', 24, 89, 98, 'mauricio@playacacao.com', 'camposm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200365, 'Pamela', 'Ruiz', '122-123','Encargado_Eventos', 24, 90, 99, 'pamela@playacacao.com', 'ruizp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200366, 'Sebastián', 'Lobo', '124-125','Contador', 24, 91, 100, 'sebastian@playacacao.com', 'lobose@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200367, 'Jimena', 'Zamora', '126-127','Ayudante_Cocina', 24, 92, 101, 'jimena@playacacao.com', 'zamoraj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200368, 'Esteban', 'Picado', '128-129','Asistente_Gerencia', 24, 102,'esteban@playacacao.com', 'picadoe@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200369, 'Adriana', 'Fonseca', '130-131','Consultor', 24, 94, 103, 'adriana@playacacao.com', 'fonsecaa@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200370, 'Julián', 'Artavia', '132-133','Mantenimiento', 25, 95, 104, 'julian@playacacao.com', 'artaviaj@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200371, 'Maricela', 'Rojas', '134-135','Community_Manager', 25, 96, 105, 'maricela@playacacao.com', 'rojasm@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200372, 'Pablo', 'González', '136-137','Encargado_Proveedores', 25, 97, 106, 'pablo@playacacao.com', 'gonzalezp@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200373, 'Tatiana', 'Leiva', '138-139','Tester', 25, 98, 108, 'tatiana@playacacao.com', 'leivat@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200374, 'Rodrigo', 'Calderón', '140-141','Supervisor', 25, 99, 109, 'rodrigo@playacacao.com', 'calderonr@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200375, 'Silvia', 'López', '142-143','Encargado_Compras', 63, 100, 119, 'silvia@playacacao.com', 'lopezs@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200377, 'Alejandro', 'Aguero', '136-137','Empleado', 25, 97, 106, 'delfino@playacacao.com', 'delfi@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200378, 'Jose', 'Araya', '138-133','Gerente', 25, 98, 108, 'jd@playacacao.com', 'josearaya@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200379, 'Freddy', 'Contreras', '134-741','Empleado', 25, 99, 109, 'fredcon@playacacao.com', 'Freddy@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200201, 'Isaac', 'Rodriguez', '142-178','Empleado', 63, 100, 119, 'Isrod@playacacao.com', 'Isaac@gmail.com','Password1234','Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200380, 'María', 'Cordero', '145-981', 'Empleado', 25, 97, 106, 'mcord@playacacao.com', 'maria@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200381, 'Luis', 'Vargas', '139-222', 'Empleado', 25, 98, 106, 'lvargas@playacacao.com', 'luisv@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200382, 'Karla', 'Jiménez', '150-333', 'Empleado', 63, 100, 107, 'karla@playacacao.com', 'kjimenez@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200383, 'Manuel', 'Cruz', '160-444', 'Empleado', 63, 99, 106, 'mcruz@playacacao.com', 'manuel@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200384, 'Andrea', 'Solano', '170-555', 'Empleado', 25, 100, 109, 'asolano@playacacao.com', 'andrea@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200385, 'Daniel', 'Ureña', '180-666', 'Empleado', 25, 98, 107, 'danielu@playacacao.com', 'daniel@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200386, 'Valeria', 'Castillo', '190-777', 'Empleado', 63, 97, 106, 'valeriac@playacacao.com', 'valeria@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200387, 'Esteban', 'Mora', '200-888', 'Empleado', 63, 99, 107, 'emora@playacacao.com', 'esteban@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200388, 'Pamela', 'Vargas', '210-999', 'Empleado', 25, 97, 108, 'pvargas@playacacao.com', 'pamela@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200389, 'Diego', 'Alfaro', '220-111', 'Empleado', 25, 98, 109, 'dalfaro@playacacao.com', 'diego@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200390, 'Camila', 'Chaves', '230-112', 'Empleado', 25, 100, 106, 'camila@playacacao.com', 'camichaves@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200391, 'Fernando', 'Rojas', '240-113', 'Empleado', 63, 97, 107, 'frojas@playacacao.com', 'fernando@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200392, 'Laura', 'Gómez', '250-114', 'Empleado', 63, 98, 109, 'lgomez@playacacao.com', 'laura@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200393, 'Javier', 'Navarro', '260-115', 'Empleado', 25, 99, 106, 'jnavarro@playacacao.com', 'javier@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200394, 'Natalia', 'Ramírez', '270-116', 'Empleado', 63, 100, 108, 'nramirez@playacacao.com', 'natalia@gmail.com', 'Password1234', 'Agregando personas');
EXEC PKT_PERSONAS.CREAR_PERSONA(1200395, 'Andrés', 'Zamora', '280-117', 'Empleado', 25, 97, 109, 'azamora@playacacao.com', 'andres@gmail.com', 'Password1234', 'Agregando personas');


EXEC PKT_PERSONAS.CREAR_PERSONA(777777, 'InvalidUser', 'InvalidUser', '00000','Cliente', 1, 1, 1, 'Invalid', 'Invalid','Invalid','Agregando personas');

--Creacion de puestos
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Mesero', 300000, 'Mesero del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Cajero', 600000, 'Cajero del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Gerente', 900000, 'Gerente general del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Asistente Gerencial', 600000, 'Asistente del gerente');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Chef Ejecutivo', 1200000, 'Encargado principal de la cocina');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Sous Chef', 950000, 'Segundo al mando en cocina');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Cocinero', 500000, 'Cocinero general del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Ayudante de Cocina', 400000, 'Asistente en cocina');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Bartender', 450000, 'Preparación y servicio de bebidas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Recepcionista', 450000, 'Atención de clientes en recepción');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Administrador', 850000, 'Encargado de operaciones administrativas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Inventario', 550000, 'Gestión de inventario y suministros');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Limpieza', 300000, 'Mantenimiento de limpieza general');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Eventos', 700000, 'Coordinación de eventos especiales');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Community Manager', 600000, 'Manejo de redes sociales del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Marketing', 650000, 'Responsable de estrategias publicitarias');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Supervisor de Turno', 700000, 'Supervisión operativa por turno');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Gerente de Ventas', 950000, 'Encargado de ventas y promociones');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Mantenimiento General', 400000, 'Reparaciones y mantenimiento básico');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Personal de Seguridad', 450000, 'Seguridad del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Contador', 900000, 'Encargado contable y financiero');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Asistente Administrativo', 550000, 'Soporte administrativo');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Compras', 650000, 'Responsable de adquisición de insumos');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Diseñador Gráfico', 600000, 'Diseño de material visual y gráfico');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Proveedores', 600000, 'Gestión y contacto con proveedores');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Asistente de Gerencia', 700000, 'Asistencia directa a la gerencia');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Consultor Externo', 1100000, 'Consultoría especializada en operaciones');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Hostess', 400000, 'Recibir y acomodar clientes');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Runner', 320000, 'Entrega de platos desde cocina a mesas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Tecnología', 800000, 'Gestión de infraestructura tecnológica');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Analista de Datos', 750000, 'Análisis de datos de operación y ventas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Capacitación', 650000, 'Formación del personal');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Calidad', 700000, 'Supervisión de estándares de calidad');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Reservaciones', 500000, 'Manejo de sistema de reservas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Operador Telefónico', 400000, 'Atención de llamadas telefónicas');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Lavaplatos', 300000, 'Encargado de limpieza de utensilios de cocina');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Ayudante de Bodega', 350000, 'Apoyo en logística y almacenamiento');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Diseñador UX/UI', 750000, 'Diseño de interfaz de usuario');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Tester de Sistemas', 700000, 'Pruebas de software y calidad');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Logística', 700000, 'Coordinación de entregas y abastecimiento');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Nómina', 850000, 'Manejo de planillas y pagos');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Supervisor de Cocina', 750000, 'Supervisión del personal de cocina');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Relaciones Públicas', 800000, 'Manejo de imagen y relaciones institucionales');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Atención al Cliente', 650000, 'Gestión de experiencia del cliente');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Fotógrafo de Productos', 500000, 'Fotografía de menú y productos');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Programador Web', 850000, 'Desarrollo del sitio web del restaurante');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Seguridad Alimentaria', 700000, 'Vigilancia de normas de higiene y seguridad');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Capacitador de Personal', 600000, 'Capacitación continua del equipo');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Proyectos', 950000, 'Gestión de proyectos estratégicos');
EXEC PKG_PUESTOS.AGREGAR_PUESTO('Encargado de Delivery', 500000, 'Coordinación de pedidos a domicilio');



--- Agregar departamentos
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Gerenncia','Departamento administrativo', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Saloneria','Departamento de salon', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Cocina','Departamento de cocina', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Caja', 'Departamento de caja y cobros', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Bar', 'Departamento de bar y bebidas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Limpieza', 'Departamento de limpieza y mantenimiento', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Recursos Humanos', 'Departamento de gestión del personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Mantenimiento', 'Departamento de mantenimiento general', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Marketing', 'Departamento de publicidad y redes', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Inventario', 'Departamento de control de inventario', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Eventos', 'Departamento de organización de eventos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Compras', 'Departamento de compras e insumos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Contabilidad', 'Departamento financiero y contable', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('TI', 'Departamento de tecnología e infraestructura', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Seguridad', 'Departamento de seguridad', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Atención al Cliente', 'Departamento de servicio al cliente', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Reservaciones', 'Departamento de reservas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Calidad', 'Departamento de aseguramiento de calidad', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Capacitación', 'Departamento de formación de personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Logística', 'Departamento de logística y distribución', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Ventas', 'Departamento de ventas y promociones', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Públicas', 'Departamento de comunicación y RP', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Diseño', 'Departamento de diseño gráfico y visual', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Legal', 'Departamento legal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Consultoría', 'Departamento de asesoría externa', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Producción', 'Departamento de producción de alimentos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Distribución', 'Departamento de reparto y entrega', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Laborales', 'Departamento de relaciones internas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Facturación', 'Departamento de facturación', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Soporte Técnico', 'Departamento de soporte TI', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Gestión de Proyectos', 'Departamento de planificación de proyectos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Decoración', 'Departamento de ambientación del local', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Servicio Express', 'Departamento de entregas rápidas', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Prensa', 'Departamento de medios y comunicación', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Redes Sociales', 'Departamento de gestión de redes', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Desarrollo', 'Departamento de innovación y desarrollo', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Análisis de Datos', 'Departamento de análisis estadístico', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Control Interno', 'Departamento de auditoría y control', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Ingeniería de Procesos', 'Departamento de mejora de procesos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Sostenibilidad', 'Departamento de responsabilidad ambiental', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Relaciones Internacionales', 'Departamento de cooperación externa', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Publicidad', 'Departamento de campañas publicitarias', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Administración de Personal', 'Departamento de manejo de personal', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Tráfico', 'Departamento de coordinación interna', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Call Center', 'Departamento de atención telefónica', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Archivo', 'Departamento de gestión documental', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Proyectos Especiales', 'Departamento de proyectos estratégicos', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Innovación', 'Departamento de mejora continua', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Transporte', 'Departamento de movilidad y transporte', 'Agregando Departamento');
EXEC PKG_DEPARTAMENTOS.AGREGAR_DEPARTAMENTO('Asistencias', 'Departamento de asistencias', 'Agregando Departamento');


--Creacion de empleados
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(10001,1,1,1000000,1184401,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,68,89999,1200364,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(22,65,900000,1200357,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(22,65,1200000,1200367,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(62,66,950000,1200360,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(61,21,500000,1200358,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(22,62,400000,1200356,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(121,98,450000,1200353,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(22,64,450000,1200351,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(95,72,850000,1200371,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(82,84,550000,1200369,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(70,78,300000,1200366,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(22,64,700000,13688,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(69,72,600000,1200346,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(82,84,650000,1200377,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(70,78,700000,1200379,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(95,81,950000,1200201,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(89,95,400000,1200380,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(93,101,450000,1200381,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(80,90,900000,1200382,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(84,89,550000,1200383,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(68,80,650000,1200384,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(86,107,600000,1200385,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(1,71,600000,1200386,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(88,69,700000,1200387,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(96,70,1100000,1200388,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(105,97,400000,1200389,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(67,98,320000,1200390,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(81,82,800000,1200391,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(63,106,750000,1200392,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(77,100,650000,1200393,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(65,91,700000,1200394,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(66,104,500000,1200395,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(98,87,400000,1345667,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(98,80,300000,1200375,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(68,71,350000,1200365,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(67,69,750000,1200354,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(98,82,700000,1200372,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(71,87,700000,1200361,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,22,850000,1238889,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,22,750000,1200378,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,22,800000,1184401,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,22,650000,1899889,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(78,75,500000,1200350,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(71,76,850000,1200370,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(99,73,700000,1200363,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(21,6,600000,1200348,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(21,67,950000,1200349,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(96,92,500000,1200362,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(100,99,600000,1200374,'Agregando Empleado');
EXEC PKG_EMPLEADOS.AGREGAR_EMPLEADO(71,96,300000,1200373,'Agregando Empleado');

--Agregar platillos
EXEC PKT_PLATILLOS.CREAR_PLATILLO('Arroz con camarones', 5000, 50, 'Agregando platillos');
EXEC CREAR_PLATILLO('Papas fritas', 2000, 100, 'Agregando platillos');
EXEC CREAR_PLATILLO('Dedos de pollo', 3000, 80, 'Agregando platillos');
EXEC CREAR_PLATILLO('Arroz con Pollo', 3500, 120, 'Platillo típico costarricense');
EXEC CREAR_PLATILLO('Casado con Carne', 4000, 110, 'Incluye arroz, frijoles, carne de res');
EXEC CREAR_PLATILLO('Ensalada César con Pollo', 3200, 90, 'Fresca y ligera');
EXEC CREAR_PLATILLO('Pizza Margarita', 4500, 80, 'Base de tomate, albahaca y mozzarella');
EXEC CREAR_PLATILLO('Pasta Alfredo', 4700, 75, 'Salsa cremosa con champiñones');
EXEC CREAR_PLATILLO('Ceviche Mixto', 5000, 65, 'Con camarón y pescado blanco');
EXEC CREAR_PLATILLO('Hamburguesa Clásica', 3800, 100, 'Pan artesanal con carne de res');
EXEC CREAR_PLATILLO('Chifrijo', 4200, 95, 'Frijoles, chicharrón y pico de gallo');
EXEC CREAR_PLATILLO('Tacos al Pastor', 4300, 70, 'Con piña, cebolla y cilantro');
EXEC CREAR_PLATILLO('Sopa Negra', 3000, 85, 'Frijoles negros con huevo duro');
EXEC CREAR_PLATILLO('Quesadillas de Pollo', 3900, 95, 'Tortilla rellena de queso y pollo');
EXEC CREAR_PLATILLO('Arroz Chaufa', 4600, 80, 'Fusión peruana-china con vegetales');
EXEC CREAR_PLATILLO('Filete de Pescado', 5200, 60, 'A la plancha con vegetales');
EXEC CREAR_PLATILLO('Gallo Pinto', 2800, 120, 'Tradicional desayuno tico');
EXEC CREAR_PLATILLO('Panqueques con Miel', 3100, 100, 'Desayuno dulce');
EXEC CREAR_PLATILLO('Burrito de Res', 4100, 90, 'Con frijoles y guacamole');
EXEC CREAR_PLATILLO('Arepas Rellenas', 3500, 85, 'Con carne mechada');
EXEC CREAR_PLATILLO('Pollo Empanizado', 3900, 95, 'Con papas fritas');
EXEC CREAR_PLATILLO('Chow Mein', 4500, 70, 'Fideos salteados estilo chino');
EXEC CREAR_PLATILLO('Crema de Ayote', 3100, 100, 'Sopa cremosa de ayote');
EXEC CREAR_PLATILLO('Tamal Asado', 3200, 75, 'Hecho con masa de maíz y relleno');
EXEC CREAR_PLATILLO('Tortilla Española', 3600, 80, 'Con papa y huevo');
EXEC CREAR_PLATILLO('Empanadas de Frijol', 2900, 95, 'Masa frita con relleno salado');
EXEC CREAR_PLATILLO('Croquetas de Pollo', 3500, 90, 'Crujientes por fuera, suaves por dentro');
EXEC CREAR_PLATILLO('Hamburguesa Vegana', 4000, 70, 'Con torta de garbanzo');
EXEC CREAR_PLATILLO('Pasta al Pesto', 4700, 85, 'Salsa de albahaca y ajo');
EXEC CREAR_PLATILLO('Crepes Dulces', 3100, 80, 'Con nutella y fruta');
EXEC CREAR_PLATILLO('Lasaña de Carne', 4900, 70, 'Capas de pasta, carne y queso');
EXEC CREAR_PLATILLO('Tarta de Queso', 3500, 100, 'Postre frío');
EXEC CREAR_PLATILLO('Canelones de Espinaca', 3700, 75, 'Rellenos vegetarianos');
EXEC CREAR_PLATILLO('Rollos Primavera', 3300, 90, 'Con salsa agridulce');
EXEC CREAR_PLATILLO('Pollo Teriyaki', 4800, 65, 'Estilo japonés');
EXEC CREAR_PLATILLO('Alitas BBQ', 4200, 95, 'Picantes o dulces');
EXEC CREAR_PLATILLO('Cazuela de Mariscos', 5500, 60, 'Con crema y vino blanco');
EXEC CREAR_PLATILLO('Pupusas Revueltas', 3600, 90, 'Queso, frijol y chicharrón');
EXEC CREAR_PLATILLO('Sushi Roll California', 5000, 70, 'Aguacate y surimi');
EXEC CREAR_PLATILLO('Fajitas Mixtas', 4600, 85, 'Res y pollo con vegetales');
EXEC CREAR_PLATILLO('Bistec Encebollado', 4400, 80, 'Clásico costarricense');
EXEC CREAR_PLATILLO('Sándwich Cubano', 4000, 100, 'Con jamón y pepinillo');
EXEC CREAR_PLATILLO('Pizza Hawaiana', 4700, 85, 'Con piña y jamón');
EXEC CREAR_PLATILLO('Cremas Heladas', 3000, 90, 'Diferentes sabores');
EXEC CREAR_PLATILLO('Costillas BBQ', 5600, 70, 'Jugosas y bien cocidas');
EXEC CREAR_PLATILLO('Ensalada de Atún', 3400, 100, 'Fresca con vinagreta');
EXEC CREAR_PLATILLO('Galletas con Helado', 3200, 95, 'Postre muy solicitado');
EXEC CREAR_PLATILLO('Milkshake de Chocolate', 3300, 90, 'Refrescante y dulce');
EXEC CREAR_PLATILLO('Panini de Pollo', 3900, 80, 'Tostado con queso');
EXEC CREAR_PLATILLO('Torta Chilena', 3700, 85, 'Postre tradicional');
EXEC CREAR_PLATILLO('Café Cappuccino', 2800, 120, 'Perfecto para la tarde');
EXEC CREAR_PLATILLO('Brownie con Helado', 3600, 90, 'Combinación perfecta');

-- Agregar menús
EXEC CREAR_MENU('Menu Vegetariano', 'Opciones sin carne, frescas y saludables', 'Agregando menus');
EXEC CREAR_MENU('Menu Vegano', 'Completamente libre de productos animales', 'Agregando menus');
EXEC CREAR_MENU('Menu Sin Gluten', 'Especial para personas con intolerancia al gluten', 'Agregando menus');
EXEC CREAR_MENU('Menu del Día', 'Platos variados que cambian diariamente', 'Agregando menus');
EXEC CREAR_MENU('Menu Desayuno', 'Variedad de desayunos típicos e internacionales', 'Agregando menus');
EXEC CREAR_MENU('Menu Almuerzo', 'Comidas fuertes y balanceadas para el mediodía', 'Agregando menus');
EXEC CREAR_MENU('Menu Cena', 'Opciones ligeras y sabrosas para la noche', 'Agregando menus');
EXEC CREAR_MENU('Menu de Mariscos', 'Especialidades del mar', 'Agregando menus');
EXEC CREAR_MENU('Menu Tico', 'Platos tradicionales costarricenses', 'Agregando menus');
EXEC CREAR_MENU('Menu Mexicano', 'Tacos, enchiladas y más delicias mexicanas', 'Agregando menus');
EXEC CREAR_MENU('Menu Italiano', 'Pastas, pizzas y sabores italianos clásicos', 'Agregando menus');
EXEC CREAR_MENU('Menu Asiático', 'Cocina oriental con toques locales', 'Agregando menus');
EXEC CREAR_MENU('Menu Parrilla', 'Carnes a la parrilla y guarniciones', 'Agregando menus');
EXEC CREAR_MENU('Menu Light', 'Platos bajos en calorías y grasas', 'Agregando menus');
EXEC CREAR_MENU('Menu Gourmet', 'Alta cocina para paladares exigentes', 'Agregando menus');
EXEC CREAR_MENU('Menu Rápido', 'Comidas rápidas para llevar', 'Agregando menus');
EXEC CREAR_MENU('Menu Fiestas', 'Menú especial para celebraciones y eventos', 'Agregando menus');
EXEC CREAR_MENU('Menu Navidad', 'Especial de temporada navideña', 'Agregando menus');
EXEC CREAR_MENU('Menu Fin de Año', 'Cierre del año con sabores especiales', 'Agregando menus');
EXEC CREAR_MENU('Menu San Valentín', 'Para una velada romántica', 'Agregando menus');
EXEC CREAR_MENU('Menu Halloween', 'Comidas temáticas para celebrar', 'Agregando menus');
EXEC CREAR_MENU('Menu Pascua', 'Opciones especiales para Semana Santa', 'Agregando menus');
EXEC CREAR_MENU('Menu de Sopas', 'Sopas tradicionales e internacionales', 'Agregando menus');
EXEC CREAR_MENU('Menu de Postres', 'Deliciosos postres caseros', 'Agregando menus');
EXEC CREAR_MENU('Menu Bebidas', 'Jugos, cócteles y refrescos', 'Agregando menus');
EXEC CREAR_MENU('Menu Café', 'Café y acompañamientos dulces', 'Agregando menus');
EXEC CREAR_MENU('Menu Internacional', 'Selección de platos de varios países', 'Agregando menus');
EXEC CREAR_MENU('Menu Premium', 'Platos exclusivos y selectos', 'Agregando menus');
EXEC CREAR_MENU('Menu BBQ', 'Costillas, hamburguesas y parrilla americana', 'Agregando menus');
EXEC CREAR_MENU('Menu Mediterráneo', 'Sabores del mar Mediterráneo', 'Agregando menus');
EXEC CREAR_MENU('Menu Saludable', 'Comida nutritiva y balanceada', 'Agregando menus');
EXEC CREAR_MENU('Menu Keto', 'Opciones bajas en carbohidratos', 'Agregando menus');
EXEC CREAR_MENU('Menu Proteico', 'Alto contenido en proteínas', 'Agregando menus');
EXEC CREAR_MENU('Menu Deportivo', 'Energía y recuperación para atletas', 'Agregando menus');
EXEC CREAR_MENU('Menu Picante', 'Para los que aman el fuego en la boca', 'Agregando menus');
EXEC CREAR_MENU('Menu Oriental', 'Fusión de sabores de Asia oriental', 'Agregando menus');
EXEC CREAR_MENU('Menu Caribeño', 'Cocina del Caribe con coco, pescado y más', 'Agregando menus');
EXEC CREAR_MENU('Menu Infantil Saludable', 'Comida divertida y nutritiva para niños', 'Agregando menus');
EXEC CREAR_MENU('Menu Económico', 'Platos sabrosos a bajo costo', 'Agregando menus');
EXEC CREAR_MENU('Menu Clásico', 'Recetas tradicionales que nunca fallan', 'Agregando menus');
EXEC CREAR_MENU('Menu Sorpresa', 'Chef’s choice para los aventureros', 'Agregando menus');
EXEC CREAR_MENU('Menu Temporada', 'Basado en ingredientes frescos del momento', 'Agregando menus');
EXEC CREAR_MENU('Menu Buffet', 'Opción libre con variedad de platillos', 'Agregando menus');
EXEC CREAR_MENU('Menu Brunch', 'Entre desayuno y almuerzo, ideal para el fin de semana', 'Agregando menus');
EXEC CREAR_MENU('Menu Romántico', 'Perfecto para una cena en pareja', 'Agregando menus');
EXEC CREAR_MENU('Menu Degustación', 'Muestras pequeñas de muchos sabores', 'Agregando menus');
EXEC CREAR_MENU('Menu Fusión', 'Combinación de distintas cocinas del mundo', 'Agregando menus');

--Agregar platillos al menu
EXEC CREAR_PLATILLO_MENU(21,1,'Agregando platillos al menu');

--Agregar pedidos
EXEC CREAR_PEDIDO(10001,10000,'Nuevo','Agregando_Pedido');

--Agregamos metodos de pago
EXEC CREAR_METODO_DE_PAGO('Tarjeta','Pago con tarjeta de debito o credito', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Tarjeta de Credito','Pago mediante tarjeta de credito bancaria.', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Efectivo','Pago con efectivo o sinpe', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Cheque','Pago con cheque', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Puntos','Pago con puntos del restaurante', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Tasa 0','Pago con tasa 0 del banco', 'Agregando Metodo de pago');
EXEC CREAR_METODO_DE_PAGO('Sinpe movil','Pago con sinpemovil', 'Agregando Metodo de pago');

--Agregamos platillos a un pedido
EXEC CREAR_ENTRADA_LISTA_PLATILLOS(2,2,'Agregando pedidos al pedido 1');
EXEC CREAR_ENTRADA_LISTA_PLATILLOS(1,2,'Agregando pedidos al pedido 1');

--Agregamos una factura
EXEC CREAR_FACTURA(2,1,0,'Agregando Factura');


--Agregar horarios
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 21:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 09:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 09:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 10:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 10:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 11:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 11:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 12:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 12:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 13:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 13:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 14:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 14:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 15:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 15:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 16:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 16:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 17:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 17:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 18:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 18:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 19:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 19:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 20:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 20:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 21:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 21:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 22:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 22:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 23:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-18 23:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 00:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 00:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 01:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 01:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 02:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 02:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 03:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 03:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 04:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 04:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 05:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 05:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 06:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 06:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 07:00', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');
EXEC CREAR_HORARIO_MESA('Disponible', TO_DATE('2025-05-19 07:30', 'YYYY-MM-DD HH24:MI'), 'Agregando horario');


---- Crear mesas
EXEC PKT_MESAS.CREAR_MESA('21',1);
EXEC PKT_MESAS.CREAR_MESA('22',21);
EXEC PKT_MESAS.CREAR_MESA('23',41);
EXEC PKT_MESAS.CREAR_MESA('24',42);
EXEC PKT_MESAS.CREAR_MESA('25',43);
EXEC PKT_MESAS.CREAR_MESA('26',44);
EXEC PKT_MESAS.CREAR_MESA('27',45);
EXEC PKT_MESAS.CREAR_MESA('28',46);
EXEC PKT_MESAS.CREAR_MESA('29',47);
EXEC PKT_MESAS.CREAR_MESA('30',48);
EXEC PKT_MESAS.CREAR_MESA('31',49);
EXEC PKT_MESAS.CREAR_MESA('32',50);
EXEC PKT_MESAS.CREAR_MESA('33',51);
EXEC PKT_MESAS.CREAR_MESA('34',52);
EXEC PKT_MESAS.CREAR_MESA('35',53);
EXEC PKT_MESAS.CREAR_MESA('36',54);
EXEC PKT_MESAS.CREAR_MESA('37',55);
EXEC PKT_MESAS.CREAR_MESA('38',56);
EXEC PKT_MESAS.CREAR_MESA('39',57);
EXEC PKT_MESAS.CREAR_MESA('40',58);
EXEC PKT_MESAS.CREAR_MESA('41',59);
EXEC PKT_MESAS.CREAR_MESA('42',60);
EXEC PKT_MESAS.CREAR_MESA('43',61);
EXEC PKT_MESAS.CREAR_MESA('44',62);
EXEC PKT_MESAS.CREAR_MESA('45',63);
EXEC PKT_MESAS.CREAR_MESA('46',64);
EXEC PKT_MESAS.CREAR_MESA('47',65);
EXEC PKT_MESAS.CREAR_MESA('48',66);
EXEC PKT_MESAS.CREAR_MESA('49',67);
EXEC PKT_MESAS.CREAR_MESA('50',68);
EXEC PKT_MESAS.CREAR_MESA('51',69);
EXEC PKT_MESAS.CREAR_MESA('52',70);
EXEC PKT_MESAS.CREAR_MESA('53',71);
EXEC PKT_MESAS.CREAR_MESA('54',72);
EXEC PKT_MESAS.CREAR_MESA('55',73);
EXEC PKT_MESAS.CREAR_MESA('56',74);
EXEC PKT_MESAS.CREAR_MESA('57',75);
EXEC PKT_MESAS.CREAR_MESA('58',76);
EXEC PKT_MESAS.CREAR_MESA('59',77);
EXEC PKT_MESAS.CREAR_MESA('60',78);
EXEC PKT_MESAS.CREAR_MESA('61',79);
EXEC PKT_MESAS.CREAR_MESA('62',80);
EXEC PKT_MESAS.CREAR_MESA('63',81);
EXEC PKT_MESAS.CREAR_MESA('64',82);
EXEC PKT_MESAS.CREAR_MESA('65',83);
EXEC PKT_MESAS.CREAR_MESA('66',84);
EXEC PKT_MESAS.CREAR_MESA('67',85);
EXEC PKT_MESAS.CREAR_MESA('68',86);
EXEC PKT_MESAS.CREAR_MESA('69',87);
EXEC PKT_MESAS.CREAR_MESA('70',88);

---- Agregar reservaciones

EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200364 ,1);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200357 ,2);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200367 ,41);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200360 ,42);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200358 ,43);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200356 ,44);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200353 ,45);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200351 ,46);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200371 ,47);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200369 ,48);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200366 ,49);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',13688 ,50);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200346 ,51);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200377 ,52);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200379 ,53);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200201 ,54);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200380 ,55);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200381 ,56);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200382 ,57);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200383 ,58);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200384 ,59);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200385 ,60);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200386 ,61);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200387 ,62);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200388 ,63);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200389 ,64);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200390 ,65);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200391 ,66);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200392 ,67);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200393 ,68);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200394 ,69);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200395 ,70);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1345667 ,71);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200375 ,72);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200365 ,73);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200354 ,74);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200372 ,75);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200361 ,76);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',12388890, 77);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200378 ,78);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1184401 ,79);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1899889 ,80);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200350 ,81);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200370 ,82);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200363 ,83);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200348 ,84);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200349 ,85);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200362 ,86);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200374 ,87);
EXEC PKT_RESERVACIONES.CREAR_RESERVACION('Confirmado',1200373 ,88);


SELECT * FROM RESERVACIONES;

SELECT * FROM MESAS;