SELECT * FROM ESTADOS WHERE ESTADO = 'Inactivo';

SELECT * FROM VISTA_ROL_PERSONA;

--Procedimiento almacenado para leer todas los ROL_PERSONA--

    PROCEDURE ENVIO_TOTAL_ROL_PERSONA (
        P_CURSOR_RESULTADO OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR_RESULTADO FOR
            SELECT ID_ROL_PERSONA, NOMBRE_LARGO_TIPO, DESCRIPCION, NIVEL_PERMISO
            FROM VISTA_ROL_PERSONA;
    END ENVIO_TOTAL_ROL_PERSONA;

--Procedimiento almacenado para leer una provincia --

    PROCEDURE ENVIO_ROL_PERSONA (
        P_ID_ROL_PERSONA NUMBER,
        P_CURSOR_RESULTADO OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR_RESULTADO FOR
            SELECT ID_ROL_PERSONA, NOMBRE_LARGO_TIPO, DESCRIPCION, NIVEL_PERMISO
            FROM VISTA_ROL_PERSONA
            WHERE ID_ROL_PERSONA = P_ID_ROL_PERSONA;
    END ENVIO_ROL_PERSONA;

--Procedimiento almacenado para actualizar una provincia--

    PROCEDURE ACTUALIZAR_ROL_PERSONA (
        P_ID_ROL_PERSONA NUMBER,
        P_NUEVO_NOMBRE_LARGO_TIPO VARCHAR,
        P_NUEVA_DESCRIPCION VARCHAR,
        P_NUEVO_NIVEL_PERMISO VARCHAR
    )
    AS
    BEGIN

        UPDATE ROL_PERSONA
        SET 
        
            NUEVO_NOMBRE_LARGO_TIPO = P_NUEVO_NOMBRE_LARGO_TIPO,
            DESCRIPCION = P_NUEVA_DESCRIPCION,
            NIVEL_PERMISO = P_NUEVO_NIVEL_PERMISO

        WHERE ID_ROL_PERSONA = P_ID_ROL_PERSONA;

        COMMIT;

    END ACTUALIZAR_ROL_PERSONA;
